<?php
/**
 * Created by IntelliJ IDEA.
 * User: gushe
 * Date: 19/08/2019
 * Time: 13:20
 */

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use DoctrineExtensions\Query\Mysql;

/**
 * ActivityUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityUserRepository extends EntityRepository
{

	public function search($type,$filters)
    {
        $em = $this->getEntityManager();

        if(!empty($filters)){
            if (isset($filters["user"])) {
                $user = $filters["user"];
            }
        }

        switch($type){
            case "list":
	            if(isset($filters["group"])){
	                switch($filters["group"]){
	                	case 1: 
	                		$list = $this->createQueryBuilder('a')
		                    	->select('a.accion','COUNT(a.id) as conta');
		                	$list->addSelect("SUM(DATEDIFF(a.salida,a.entrada)) as duration");
	                		break;
	                	case 2:
	                		$list = $this->createQueryBuilder('a')
		                    	->select('u.id as usercreatedid','u.name as creator','COUNT(a.id) as conta');
		                	$list->addSelect("SUM(DATEDIFF(a.salida,a.entrada)) as duration");
	                		break;
	                	case 3:
	                		$list = $this->createQueryBuilder('a')
		                    	->select('ms.id','ms.name','COUNT(a.id) as conta');
		                	$list->addSelect("SUM(DATEDIFF(a.salida,a.entrada)) as duration");
	                		break;
	                	case 4:
	                		$list = $this->createQueryBuilder('a')
		                    	->select('a.accion','u.id as usercreatedid','u.name as creator','COUNT(a.id) as conta');
		                	$list->addSelect("SUM(DATEDIFF(a.salida,a.entrada)) as duration");
	                		break;
	                	case 5:
	                		$list = $this->createQueryBuilder('a')
		                    	->select('a.accion','ms.id','ms.name','COUNT(a.id) as conta');
		                	$list->addSelect("SUM(DATEDIFF(a.salida,a.entrada)) as duration");
	                		break;
	                	case 6:
	                		$list = $this->createQueryBuilder('a')
		                    	->select('ms.id','ms.name','u.id as usercreatedid','u.name as creator','COUNT(a.id) as conta');
		                	$list->addSelect("SUM(DATEDIFF(a.salida,a.entrada)) as duration");
	                		break;
	                	case 7:
	                		$list = $this->createQueryBuilder('a')
		                    	->select('a.accion','ms.id','ms.name','u.id as usercreatedid','u.name as creator','COUNT(a.id) as conta');
		                	$list->addSelect("SUM(DATEDIFF(a.salida,a.entrada)) as duration");
	                		break;
	                }
	            }
	            else{

                	$list = $this->createQueryBuilder('a')
                    	->select('a.id','i.id id_reg', 'i.usercreatedid','ms.name','u.name as creator','a.entrada','a.salida','m.lote','m.material','m.equipo','m.workordersap','i.status','s.id as step','i.in_edition','a.accion');
                	$list->addSelect("(DATEDIFF(a.salida,a.entrada)) as duration");
                }

                break;
            case "count":
                $list = $this->createQueryBuilder('a')
                    ->select('COUNT(a.id) as conta');
                    
                break;
        }

        $list->leftJoin("a.stepEntity", "s")
        	->leftJoin("s.instancia_workflow", "i")
            ->leftJoin("s.master_step", "ms")
            ->leftJoin("a.userEntiy", "u")
            ->leftJoin("i.metaData", "m")
            ->andWhere('a.actionID>0')
            ->andWhere('a.status=1');

        if($type=="list" && !isset($filters["group"])){
            $list->orderBy('i.id', 'DESC');
        }



        if(!empty($filters)){

            if(isset($filters["id"])){
                $list->andWhere('i.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["plantilla_id"])){
                $list->andWhere('ms.plantilla_id=:plantilla_id');
                $list->setParameter('plantilla_id', $filters["plantilla_id"]);
            }

            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('ms.name LIKE :name'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["creator"])){
                $terms = explode(" ", $filters["creator"]);
                foreach($terms as $key => $term){
                    $list->andWhere('u.name LIKE :creator'.$key);
                    $list->setParameter('creator'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["content"])){
                $terms = explode(" ", $filters["content"]);
                foreach($terms as $key => $term){
                    $list->andWhere('s.stepDataValue LIKE :content'.$key);
                    $list->setParameter('content'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["lot"])){
                $list->andWhere('m.lote=:lot');
                $list->setParameter('lot', $filters["lot"]);
            }

            if(isset($filters["material"])){
                $list->andWhere('m.material=:material');
                $list->setParameter('material', $filters["material"]);
            }

            if(isset($filters["equipment_number"])){
                $list->andWhere('m.equipo=:equipment_number');
                $list->setParameter('equipment_number', $filters["equipment_number"]);
            }

            if(isset($filters["sap"])){
                $list->andWhere('m.workordersap=:sap');
                $list->setParameter('sap', $filters["sap"]);
            }


            if(isset($filters["action"])){
                switch($filters["action"]){
                    case 6: 
                        $list->andWhere('a.actionID IN (1,2,4,5)');
                        break;
                    default:
                        $list->andWhere('a.actionID=:action');
                        $list->setParameter('action', $filters["action"]);
                }
                
            }

            if(isset($filters["from"])){
                $list->andWhere('a.entrada>=:from');
                $list->setParameter('from', $filters["from"]);
            }

            if(isset($filters["until"])){
                $list->andWhere('a.salida<=:until');
                $list->setParameter('until', $filters["until"]." 23:59:00");
            }

            if(isset($filters["group"])){
                switch($filters["group"]){
                	case 1: 
                		$list->groupBy('a.actionID')
                        ->addGroupBy('a.accion');
                		break;
                	case 2:
                		$list->groupBy('u.id')
                        ->addGroupBy('u.name');
                		break;
                	case 3:
                		$list->groupBy('ms.id')
                        ->addGroupBy('ms.name');
                		break;
                	case 4:
                		$list->groupBy('a.actionID')
                			->addGroupBy('u.id')
                            ->addGroupBy('a.accion')
                            ->addGroupBy('u.id')
                            ->addGroupBy('u.name');
                		break;
                	case 5:
                		$list->groupBy('a.actionID')
                			->addGroupBy('ms.id')
                            ->addGroupBy('a.accion')
                            ->addGroupBy('ms.name');
                		break;
                	case 6:
                		$list->groupBy('u.id')
                			->addGroupBy('ms.id')
                            ->addGroupBy('ms.name')
                            ->addGroupBy('u.id')
                            ->addGroupBy('u.name');
                		break;
                	case 7:
                		$list->groupBy('u.id')
                			->addGroupBy('ms.id')
                			->addGroupBy('a.actionID')
                            ->addGroupBy('a.accion')
                            ->addGroupBy('ms.name')
                            ->addGroupBy('u.id')
                            ->addGroupBy('u.name');
                		break;
                }
            }

        }


        if(isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();


        switch($type){
            case "list":
                return $query->getResult();
                break;
            case "count":
            	if(!isset($filters["group"])){
	                return $query->getSingleResult()["conta"];
	            }
	            else{
	            	return count($query->getResult());
	            }
                break;
        }
    }
}