<?php
/**
 * Created by IntelliJ IDEA.
 * User: gushe
 * Date: 19/08/2019
 * Time: 13:20
 */

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * ActivityUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityUserRepository extends EntityRepository
{


}