<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchiveSignaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveSignaturesRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('ars')
            ->select('IDENTITY(ars.archiveCategory) category', 'IDENTITY(ars.archivePreservation) preservation', 'IDENTITY(ars.archiveType) type', 'IDENTITY(ars.record) record','a.name action', 'u.name user', 'ars.description', 'ars.modified','ars.id','ars.attachment')
            ->leftJoin("ars.archiveAction", "a")
            ->leftJoin("ars.userEntiy", "u")
            ->orderBy('ars.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('ars')
            ->select('COUNT(ars.id) as conta')
            ->leftJoin("ars.archiveAction", "a")
            ->leftJoin("ars.userEntiy", "u");

        $list = self::fillFilersQuery($filters, $list);
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }


    private function fillFilersQuery($filters, $list){

        if(!empty($filters)){
            if(isset($filters["relational"])){
                $list->andWhere('ars.archiveCategory=:id1 OR ars.archivePreservation=:id2 OR ars.record=:id3 OR ars.archiveType=:id4');
                $list->setParameter('id1', $filters["relational"]);
                $list->setParameter('id2', $filters["relational"]);
                $list->setParameter('id3', $filters["relational"]);
                $list->setParameter('id4', $filters["relational"]);
            }

            if(isset($filters["id"])){
                $list->andWhere('ars.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["action"])){
                $list->andWhere("a.id=:action");
                $list->setParameter('action', $filters["action"]);
            }

            if(isset($filters["type"])){
                switch($filters["type"]){
                    case "category":
                        $list->andWhere("ars.archiveCategory IS NOT NULL");
                        break;
                    case "preservation":
                        $list->andWhere("ars.archivePreservation IS NOT NULL");
                        break;
                    case "type":
                        $list->andWhere("ars.archiveType IS NOT NULL");
                        break;
                    case "record":
                        $list->andWhere("ars.record IS NOT NULL");
                        break;
                }
            }

            if(isset($filters["user"])){
                $terms = explode(" ", $filters["user"]);
                foreach($terms as $key => $term){
                    $list->andWhere('u.name LIKE :user'.$key);
                    $list->setParameter('user'.$key, '%' . $term. '%');
                }
            }
        }

        return $list;
    }
}
