<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchiveSignaturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveSignaturesRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('ars')
            ->select('IDENTITY(ars.archiveCategory) category', 'IDENTITY(ars.archivePreservation) preservation', 'IDENTITY(ars.archiveType) type', 'IDENTITY(ars.record) record', 'IDENTITY(ars.archiveAz) az', 'IDENTITY(ars.archiveLocation) location','a.name action', 'u.name user', 'ars.description', 'ars.modified','ars.id','ars.attachment','a.id actionId','us.id useStateId','u2.name user2', 'ars2.description description2', 'ars2.modified modified2', 'ars2.id patern','ar.link','ars.changes','ar.uniqueNumber recordName','relc.name categoryName','relp.name preservationName','relaz.code azName','relt.name typeName')
            ->leftJoin("ars.archiveAction", "a")
            ->leftJoin("ars.userEntiy", "u")
            ->leftJoin("ars.record", "ar")
            ->leftJoin("ar.useState", "us")
            ->leftJoin("ar.state", "s")
            ->leftJoin("ars.patern", "ars2")
            ->leftJoin("ars2.userEntiy", "u2")
            ->leftJoin("ars.archiveCategory", "relc")
            ->leftJoin("ars.archivePreservation", "relp")
            ->leftJoin("ars.archiveAz", "relaz")
            ->leftJoin("ars.archiveType", "relt")
            ->orderBy('ars.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('ars')
            ->select('COUNT(ars.id) as conta')
            ->leftJoin("ars.archiveAction", "a")
            ->leftJoin("ars.userEntiy", "u")
            ->leftJoin("ars.record", "ar");

        $list = self::fillFilersQuery($filters, $list);
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }


    private function fillFilersQuery($filters, $list){

        if(!empty($filters)){
            if(isset($filters["relational"])){
                $list->andWhere('ars.archiveCategory=:id1 OR ars.archivePreservation=:id2 OR ars.record=:id3 OR ars.archiveType=:id4 OR ars.archiveAz=:id5');
                $list->setParameter('id1', $filters["relational"]);
                $list->setParameter('id2', $filters["relational"]);
                $list->setParameter('id3', $filters["relational"]);
                $list->setParameter('id4', $filters["relational"]);
                $list->setParameter('id5', $filters["relational"]);
            }

            if(isset($filters["id"])){
                $list->andWhere('ars.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["action"])){
                $list->andWhere("a.id=:action");
                $list->setParameter('action', $filters["action"]);
            }

            if(isset($filters["actions"])){
                $list->andWhere("a.id IN (:actions)");
                $list->setParameter('actions', $filters["actions"]);
            }

            if(isset($filters["not_available"])){
                $list->andWhere("ars.notAvailable IS NULL");
            }

            if(isset($filters["areas"])){
                $list->andWhere('ar.area IN (:areas)');
                $list->setParameter('areas', $filters["areas"]);
            }

            if(isset($filters["recordId"])){
                $list->andWhere('ar.id = :recordId');
                $list->setParameter('recordId', $filters["recordId"]);
            }

            if(isset($filters["type"])){
                switch($filters["type"]){
                    case "category":
                        $list->andWhere("ars.archiveCategory IS NOT NULL");
                        break;
                    case "preservation":
                        $list->andWhere("ars.archivePreservation IS NOT NULL");
                        break;
                    case "type":
                        $list->andWhere("ars.archiveType IS NOT NULL");
                        break;
                    case "record":
                        $list->andWhere("ars.record IS NOT NULL");
                        break;
                    case "az":
                        $list->andWhere("ars.archiveAz IS NOT NULL");
                        break;
                    case "location":
                        $list->andWhere("ars.archiveLocation IS NOT NULL");
                        break;
                    case "state":
                        $list->andWhere("ars.archiveState IS NOT NULL");
                        break;
                }
            }

            if(isset($filters["user"])){
                $terms = explode(" ", $filters["user"]);
                foreach($terms as $key => $term){
                    $list->andWhere('u.name LIKE :user'.$key);
                    $list->setParameter('user'.$key, '%' . $term. '%');
                }
            }
        }

        return $list;
    }
}
