<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\QueryException;
use Doctrine\ORM\QueryBuilder;

/**
 * ArchiveCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveCategoriesRepository extends EntityRepository
{

    /**
     * @param string[] $filters
     * @param int $paginate
     * @return array|int|string
     */
    public function list(array $filters, $paginate = 1)
    {
        $list = $this->createQueryBuilder('ac')
            ->select('ac')
            ->orderBy('ac.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);

        if ($paginate == 1 && isset($filters["limit_from"])) {
            $list->setFirstResult($filters["limit_from"] * $filters["limit_many"])->setMaxResults(
                $filters["limit_many"]
            );
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    /**
     * @param array $filters
     * @return mixed
     */
    public function count($filters = [])
    {
        $list = $this->createQueryBuilder('ac')
            ->select('COUNT(ac.id) as conta');

        $list = self::fillFilersQuery($filters, $list);
        $query = $list->getQuery();

        try {
            $result = $query->getSingleScalarResult();
        } catch (QueryException $e) {
            $result = 0;
        }

        return $result;
    }

    /**
     * @param array $filters
     * @param QueryBuilder $list
     * @return QueryBuilder
     */
    private function fillFilersQuery(array $filters, QueryBuilder $list)
    {
        $list->andWhere('ac.deletedAt is null');

        if (isset($filters["name"])) {
            $terms = explode(" ", $filters["name"]);
            foreach($terms as $key => $term){
                $list->andWhere('ac.name LIKE :name'.$key);
                $list->setParameter('name'.$key, '%' .$term . '%');
            }
        }


        if (isset($filters["active"])) {
            $list->andWhere('ac.active = :active');
            $list->setParameter('active', $filters["active"]);
        }

        return $list;
    }

    public function listToArray(): array
    {
        $list = $this->createQueryBuilder('ac')
            ->select('ac')
            ->orderBy('ac.id', 'DESC');

        $query = $list->getQuery();

        return $query->getArrayResult();
    }

}
