<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchiveLocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveLocationsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('qr')
            ->select('qr')
            ->orderBy('qr.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('qr')
            ->select('COUNT(qr.id) as conta');

        $list = self::fillFilersQuery($filters, $list);
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }


    private function fillFilersQuery($filters, $list){

        if(!empty($filters)){
            if(isset($filters["id"])){
                $list->andWhere('qr.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["building"])){
                $terms = explode(" ", $filters["building"]);
                foreach($terms as $key => $term){
                    $list->andWhere('qr.building LIKE :building'.$key);
                    $list->setParameter('building'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["shelf"])){
                $terms = explode(" ", $filters["shelf"]);
                foreach($terms as $key => $term){
                    $list->andWhere('qr.shelf LIKE :shelf'.$key);
                    $list->setParameter('shelf'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["passage"])){
                $terms = explode(" ", $filters["passage"]);
                foreach($terms as $key => $term){
                    $list->andWhere('qr.passage LIKE :passage'.$key);
                    $list->setParameter('passage'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["cabinet"])){
                $terms = explode(" ", $filters["cabinet"]);
                foreach($terms as $key => $term){
                    $list->andWhere('qr.cabinet LIKE :cabinet'.$key);
                    $list->setParameter('cabinet'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["others"])){
                $terms = explode(" ", $filters["others"]);
                foreach($terms as $key => $term){
                    $list->andWhere('qr.others LIKE :others'.$key);
                    $list->setParameter('others'.$key, '%' . $term. '%');
                }
            }
        }

        return $list;
    }
}
