<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AreasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreasRepository extends EntityRepository
{
	public function list($filters)
    {
        $em = $this->getEntityManager();


        $list = $this->createQueryBuilder('a')
            ->select('a.id', 'a.name')
            ->andWhere('a.isActive=1')
            ->orderBy('a.id', 'DESC');

        if(!empty($filters)){
            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('a.name LIKE :name'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                }
                
            }
        }

        if(isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array(),$types = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('a')
            ->select('COUNT(a.id) as conta')
            ->andWhere('a.isActive=1');

        if(!empty($filters)){
            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('a.name LIKE :name'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                }
                
            }
        }
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }
}
