<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{
    /**
     * List of Categories
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listTiposContratos()
    {
        $sort = "name";
        $list = $this->createQueryBuilder('n')
            ->select('n.id, n.name');

        $list->orderBy('n.' . $sort, 'ASC');


        $paginator = new Paginator($list);
        //this is a hack to be able to choose some certain fields
        $paginator->setUseOutputWalkers(false);

        return $paginator;
    }

    /**
     * Counts the total number of news
     *
     * @return int
     */
    public function countTotal()
    {
        $qb = $this->createQueryBuilder('n');
        $qb->select('COUNT(n)');

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }
}
