<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContractsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('c')
            ->select('c.id', 'c.name')
            ->andWhere('c.isActive=1')
            ->orderBy('c.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);
        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }
        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters)
    {
        $list = $this->createQueryBuilder('c')
            ->select('COUNT(c.id) as conta')
            ->leftJoin("c.type", "t")
            ->andWhere('c.isActive=1');

        $list = self::fillFilersQuery($filters, $list);
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }

    private function fillFilersQuery($filters, $list){
        if(isset($filters["name"])){
            $terms = explode(" ", $filters["name"]);
            foreach($terms as $key => $term){
                $list->andWhere('c.name LIKE :name'.$key);
                $list->setParameter('name'.$key, '%' . $term. '%');
            }
        }

    	return $list;
    }
}
