<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CVRecordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVRecordsRepository extends EntityRepository
{
	public function search($type,$filters)
    {
        $em = $this->getEntityManager();

        if(!empty($filters)){
            if (isset($filters["user"])) {
                $user = $filters["user"];
                $groups=array();
                foreach($user->getGroups() as $uniq_group){
                    $groups[]=$uniq_group->getGroup();
                }
            }
        }

        $require_action="CASE  WHEN 
            (sig.user=:eluser1 
                OR
                (
                    t.correlative=TRUE AND sig.user IS NULL AND  (w.user=:eluser1 OR (w.group IN (:groups) AND :eluser2 NOT IN (SELECT IDENTITY(vvv1.user) FROM Nononsense\HomeBundle\Entity\CVWorkflow vvv1 WHERE vvv1.record=i.id)  AND :eluser2 NOT IN (SELECT IDENTITY(vvv2.user) FROM Nononsense\HomeBundle\Entity\CVSignatures vvv2 LEFT JOIN  Nononsense\HomeBundle\Entity\CVActions vvv3 WITH vvv2.action=vvv3.id WHERE vvv2.record=i.id AND (vvv3.type!=a.type OR vvv2.finish=TRUE)) ))
                )
                OR
                (
                    t.correlative=FALSE AND sig.user IS NULL AND (
                         :eluser2 IN (SELECT IDENTITY(vvv5.user) FROM Nononsense\HomeBundle\Entity\CVWorkflow vvv5 LEFT JOIN  Nononsense\HomeBundle\Entity\TMCumplimentations vvv11 WITH vvv5.type=vvv11.id WHERE vvv5.record=i.id AND vvv5.signed=FALSE AND vvv11.tmType=s.type) AND :eluser2 NOT IN (SELECT IDENTITY(vvv6.user) FROM Nononsense\HomeBundle\Entity\CVSignatures vvv6 LEFT JOIN  Nononsense\HomeBundle\Entity\CVActions vvv7 WITH vvv6.action=vvv7.id WHERE vvv6.record=i.id AND (vvv7.type!=a.type OR vvv6.finish=TRUE))
                    )
                )
                OR
                (
                    t.correlative=FALSE AND sig.user IS NULL AND (SELECT COUNT(vvv8.id) FROM Nononsense\HomeBundle\Entity\CVWorkflow vvv8  LEFT JOIN  Nononsense\HomeBundle\Entity\TMCumplimentations vvv12 WITH vvv8.type=vvv12.id WHERE vvv8.record=i.id AND vvv12.tmType=s.type AND vvv8.signed=FALSE AND vvv8.group IN (:groups))>0  AND :eluser2 NOT IN (SELECT IDENTITY(vvv9.user) FROM Nononsense\HomeBundle\Entity\CVSignatures vvv9 LEFT JOIN  Nononsense\HomeBundle\Entity\CVActions vvv10 WITH vvv9.action=vvv10.id WHERE vvv9.record=i.id AND (vvv10.type!=a.type OR vvv9.finish=TRUE))
                )
            ) THEN 1 ELSE 0 END";

        switch($type){
            case "list":
                $list = $this->createQueryBuilder('i')
                    ->select('i.id', 't.name','u.name creator','i.created','i.modified','t.logbook','s.name state','i.inEdition','t.logbook','a.nameAlternative pendingAction','sigu.id idNextSigner','ty.name type','s.final finalState','s.color colorState','s.icon iconState','s.canBeOpened canBeOpenedState','s.nameAlternative alternativeState','ty.id type_id','sig.version','a.id action','s.id state_id');

                $list->addSelect($require_action." AS requireAction");

                if(!empty($filters) && isset($filters["have_json"])){
                    $list->addSelect('i.json');
                }

                break;
            case "count":
                $list = $this->createQueryBuilder('i')
                    ->select('COUNT(i.id) as conta');
                break;
        }

        if($type=="list" || isset($filters["pending_for_me"])){
            $list->setParameter('eluser1', $user);
            $list->setParameter('eluser2', $user->getId());
            $list->setParameter('groups', $groups);
        }
        

        $list->leftJoin("i.template", "t")
            ->leftJoin("i.user", "u")
            ->leftJoin("i.state", "s")
            ->leftJoin("i.cvWorkflows", "w", "WITH", "(w.id = (SELECT MIN(aux.id) FROM Nononsense\HomeBundle\Entity\CVWorkflow aux WHERE aux.record=i.id AND aux.signed=FALSE))")
            ->leftJoin("i.cvSignatures", "sig", "WITH", "(sig IS NULL OR sig.id = (SELECT MAX(aux2.id) FROM Nononsense\HomeBundle\Entity\CVSignatures aux2 WHERE aux2.record=i.id AND aux2.signed=FALSE))")
            ->leftJoin("i.cvSignatures", "last", "WITH", "(last.id = (SELECT MAX(aux3.id) FROM Nononsense\HomeBundle\Entity\CVSignatures aux3 WHERE aux3.record=i.id AND aux3.signed=TRUE))")
            ->leftJoin("sig.action", "a")
            ->leftJoin("s.type", "ty")
            ->leftJoin("sig.user", "sigu");
            

        if($type=="list"){
            $list->orderBy('i.id', 'DESC');
        }



        if(!empty($filters)){

            if(isset($filters["id"])){
                $list->andWhere('i.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["have_json"])){
                $list->andWhere('i.json IS NOT NULL');
            }

            if(isset($filters["not_this"])){
                $list->andWhere('i.id!=:not_this');
                $list->setParameter('not_this', $filters["not_this"]);
            }

            if(isset($filters["plantilla_id"])){
                $list->andWhere('t.id=:plantilla_id');
                $list->setParameter('plantilla_id', $filters["plantilla_id"]);
            }

            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('t.name LIKE :name'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["creator"])){
                $terms = explode(" ", $filters["creator"]);
                foreach($terms as $key => $term){
                    $list->andWhere('u.name LIKE :creator'.$key);
                    $list->setParameter('creator'.$key, '%' . $term. '%');
                }
            }


            if(isset($filters["content"])){
                $terms = explode(" ", $filters["content"]);
                foreach($terms as $key => $term){
                    $list->andWhere('last.json LIKE :content'.$key);
                    $list->setParameter('content'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["fll"]) && $filters["fll"]=="1"){
                $fll=1;
            }
            else{
                $fll=0;
            }

            if(isset($filters["status"])){
                switch($filters["status"]){
                    case 7:
                        $list->andWhere('i.state=7 OR i.state=8');
                        break;
                    default:
                        $list->andWhere('i.state=:state');
                        $list->setParameter('state', $filters["status"]);
                        break;
                }

            }

            if (isset($filters["pending_for_me"])) {
                $require_action=str_replace("vvv", "zzz", $require_action);
                $list->andWhere($require_action.'=1');
            }


            if(isset($filters["from"])){
                $list->andWhere('i.created>=:from');
                $list->setParameter('from', $filters["from"]);
            }

            if(isset($filters["until"])){
                $list->andWhere('i.created<=:until');
                $list->setParameter('until', $filters["until"]." 23:59:00");
            }

            if(isset($filters["var"]) && isset($filters["value"])){
                $list->andWhere("ISJSON(last.json) > 0");
                $list->andWhere("JSON_VALUE(last.json, :var) LIKE :value");
                $list->setParameter('var', '$.data.'.$filters["var"]);
                $list->setParameter('value', '%'.$filters["value"].'%');
            }

            if(isset($filters["code_unique"])){
                $strlen=strlen(json_encode($filters["code_unique"]));
                $list->andWhere("LENGTH(i.codeUnique)=:strlen");
                $list->andWhere("ISJSON(i.codeUnique) > 0");
                $list->setParameter('strlen', $strlen);
                $cu=0;
                foreach($filters["code_unique"] as $key_unique => $value_unique){
                    $list->andWhere("JSON_VALUE(i.codeUnique, :var".$cu.") LIKE :value".$cu);
                    $list->setParameter('var'.$cu, '$.'.$key_unique);
                    $list->setParameter('value'.$cu, $value_unique);
                    $cu++;
                }
            }

            if(isset($filters["have_signature"])){
                $list->andWhere('last.signed=TRUE');
            }

        }


        if(isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();


        switch($type){
            case "list":
                return $query->getResult();
                break;
            case "count":
                return $query->getSingleResult()["conta"];
                break;
        }
    }
}
