<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CVRecordsHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVRecordsHistoryRepository extends EntityRepository
{
	public function list($type,$filters)
	{
		$list = $this->createQueryBuilder('ish');

        switch($type){
            case "list": $list->select("ish.id,r.id recordId,t.name templateName,e.numberSignature,ish.field,ish.index,ish.value,ish.prevValue,u.name userName,e.modified,ish.lineOptions");break;
            case "count": $list->select("COUNT(ish.id) conta");break;
        }

        $list->join("ish.signature", "e")
    	->join("e.user", "u")
    	->join("e.record", "r")
        ->join("r.template", "t");

        if(isset($filters["content"])){
            $terms = explode(" ", $filters["content"]);
            foreach($terms as $key => $term){
                $list->andWhere('e.json LIKE :content_'.$key);
                $list->setParameter('content_'.$key, '%'.$term.'%');
            }
        }

        if (isset($filters['field'])) {
        	$list->andWhere('ish.field = :field');
        	$list->setParameter('field', $filters['field']);
        }

        if (isset($filters['index'])) {
        	$list->andWhere('ish.index = :index');
        	$list->setParameter('index', $filters['index']);
        }

        if (isset($filters['value'])) {
        	$list->andWhere('ish.value = :value');
        	$list->setParameter('value', $filters['value']);
        }

        if (isset($filters['creator'])) {
        	$list->andWhere('u.username = :username');
        	$list->orWhere('u.email = :username');
        	$list->setParameter('username', $filters['creator']);
        }

        if (isset($filters['name'])) {
        	$list->andWhere('t.name LIKE :name');
        	$list->setParameter('name', '%'.$filters['name'].'%');
        }

        if (isset($filters['id'])) {
        	$list->andWhere('r.id = :id');
        	$list->setParameter('id', $filters['id']);
        }

        if($type!="count"){
            $list->orderBy('ish.id', 'DESC');
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        switch($type){
            case "list": return $query->getResult();break;
            case "count": return $query->getSingleResult()["conta"];break;
        }
	}
}
