<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CVStatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVStatesRepository extends EntityRepository
{
    public function list()
    {
        $list = $this->createQueryBuilder('c')
            ->select('c.id, c.name')
            ->orderBy('c.id', 'DESC');

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getFinalStates()
    {
        $list = $this->createQueryBuilder('c')
            ->select('c.id, c.name')
            ->where("c.final = true")
            ->orderBy('c.id', 'DESC');

        $query = $list->getQuery();

        return $query->getResult();
    }
}
