<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DelegationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelegationsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('d')
            ->select('d.id', 'u.name', 'u2.name sustituteName','u.id userId', 'u2.id sustituteId', 't.name typeName', 't.id typeId', 'd.created', 'd.deleted')
            ->leftJoin("d.type", "t")
            ->leftJoin("d.user", "u")
            ->leftJoin("d.sustitute", "u2")
            ->orderBy('d.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('d')
            ->select('COUNT(d.id) as conta')
            ->leftJoin("d.type", "t")
            ->leftJoin("d.user", "u")
            ->leftJoin("d.sustitute", "u2");

        $list = self::fillFilersQuery($filters, $list);
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }


    private function fillFilersQuery($filters, $list){

        if(!empty($filters)){
            if(isset($filters["id"])){
                $list->andWhere('d.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["name"])){
                $list->andWhere("u.name LIKE '%".$filters["name"]."%'");
            }

            if(isset($filters["name2"])){
                $list->andWhere("u2.name LIKE '%".$filters["name2"]."%'");
            }

            if(isset($filters["active"]) && $filters["active"]=="1"){
                $list->andWhere("d.deleted IS NULL");
            }
        }

        return $list;
    }
}
