<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsRepository extends EntityRepository
{
	public function list($filters)
    {
        $em = $this->getEntityManager();


        $list = $this->createQueryBuilder('d')
            ->select('d.id', 'd.name', 't.name as nameType')
            ->leftJoin("d.type", "t")
            ->andWhere('d.isActive=1')
            ->orderBy('d.id', 'DESC');

        if(!empty($filters)){
            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('d.name LIKE :name'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                }
                
            }

            if(isset($filters["type"])){
                $list->andWhere('d.type=:type');
                $list->setParameter('type', $filters["type"]);
            }
        }

        if(isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array(),$types = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('d')
            ->select('COUNT(d.id) as conta')
            ->leftJoin("d.type", "t")
            ->andWhere('d.isActive=1');

        if(!empty($filters)){
            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('d.name LIKE :name'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                }
                
            }

            if(isset($filters["type"])){
                $list->andWhere('d.type=:type');
                $list->setParameter('type', $filters["type"]);
            }
        }
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }

}
