<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Instancias_StepsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanciasStepsRepository extends EntityRepository
{
    /**
     * List of Instancias_Steps with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listInstanciasSteps($sort = 'position', $id = '0')
    {
        $list = $this->createQueryBuilder('n')
            ->join('n.master_step', 'ms')
            ->select('n.id, n.workflow_id, n.master_step_id, n.isActive, n.dependsOn, n.rules, n.notification, n.status_id, n.modified, n.usage_id, n.token, ms.name','ms.plantilla_id','ms.cloneable','ms.block','ms.optional')
            ->andWhere('n.workflow_id = :id')
            ->setParameter('id', '' . $id . '');


        $list->orderBy('ms.' . $sort, 'ASC');


        $paginator = new Paginator($list);
        //this is a hack to be able to choose some certain fields
        $paginator->setUseOutputWalkers(false);

        return $paginator;
    }

    /**
     * Counts the total number of news
     *
     * @return int
     */
    public function countTotal()
    {
        $qb = $this->createQueryBuilder('n');
        $qb->select('COUNT(n)');

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }

    /**
     * List of Instancias_Steps completed by workflow id ordered by position
     *
     * @param int $workflowid
     * @param int $status_id
     * @param string $sort
     * @return Paginator
     */
    public function listInstanciasStepsByWorkflowIdAndStatus($workflowid = '1', $status_id = '4',$sort = 'position')
    {
        $list = $this->createQueryBuilder('n')
            ->join('n.master_step', 'ms')
            ->select('n.id, n.workflow_id, n.master_step_id, n.isActive, n.dependsOn, n.rules, n.notification, n.status_id, n.modified, n.usage_id, n.token, ms.name','ms.plantilla_id','ms.cloneable','ms.block','ms.optional')
            ->andWhere('n.workflow_id = :id and n.status_id = :status')
            //->setParameter('id', '' . $workflowid . '')
            ->setParameter('status', '' . $status_id . '')
            ->orderBy('ms.' . $sort, 'ASC');



        $paginator = new Paginator($list);

        return $paginator;
    }

    public function getProteccionStock($dateString){
        $list = $this->createQueryBuilder('n')
            ->select('n.id')
            ->andWhere('n.master_step_id = 160')
            ->join("n.instancia_workflow", "iw")
            ->andWhere('n.status_id not in (:status)')
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->andWhere('iw.created = :create')
            ->setParameter('status', array(0,3))
            ->setParameter('create', $dateString)
            ->orderBy('n.id', 'ASC');


        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getProteccionStockTotal(){
        $list = $this->createQueryBuilder('n')
            ->select('n.id','metadata.codigo_proveedor')
            ->andWhere('n.master_step_id = 160')
            ->join("n.instancia_workflow", "iw")
            ->leftJoin("iw.metaData", "metadata")
            ->andWhere("iw.description like '%Protección de Stock%' ")
            ->andWhere('iw.status != 20')
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->orderBy('n.id', 'ASC');


        $query = $list->getQuery();

        return $query->getResult();
    }


    public function getMargenStock($dateString){
        $list = $this->createQueryBuilder('n')
            ->select('n.id')
            ->andWhere('n.master_step_id = 159')
            ->join("n.instancia_workflow", "iw")
            ->andWhere('n.status_id not in (:status)')
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->andWhere('iw.created = :create')
            ->setParameter('status', array(0,3))
            ->setParameter('create', $dateString)
            ->orderBy('n.id', 'ASC');


        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getInstanciasStepsDescuentoLogistico($CifProveedor, $arrayAnyosFiltro, $arrayPlantillasFiltro, $fechaDesde, $fechaHasta, $arrayEstadosFiltro,$arrayFlujosFiltro,$CodigoProveedorFiltro,$NameProv){

        /*

            ->andWhere('n.usercreatedid != 22')
            //->andWhere('iw.status not in (0,3,8,20)')
            ->andWhere('iw.status not in (20)')
         */
        $list = $this->createQueryBuilder('n')
            ->andWhere('n.master_step_id in (:flujos)')
            ->join("n.instancia_workflow", "iw")
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->andWhere('iw.status not in (0,3,8,20)')
            ->setParameter('flujos', $arrayFlujosFiltro)
            ->orderBy('n.id', 'ASC');

        $list->andWhere('iw.year in (:year)');
        $list->setParameter('year', $arrayAnyosFiltro);


        $list->andWhere('iw.master_workflow in (:mw)');
        $list->setParameter('mw', $arrayPlantillasFiltro);

        $list->andWhere('iw.status in (:st)');
        $list->setParameter('st', $arrayEstadosFiltro);

        if ($fechaDesde != "") {
            $list->andWhere('iw.modified = :desde');
            $list->setParameter('desde', $fechaDesde);
        }
        if ($fechaHasta != "") {
            $list->andWhere('iw.modified = :hasta');
            $list->setParameter('hasta', $fechaHasta);
        }



        if ($CodigoProveedorFiltro != "") {
            $leftJoinMetaData = true;
            $list->leftJoin("iw.metaData", "metadata");
            $list->andWhere('metadata.codigo_proveedor = :codprov');
            $list->setParameter('codprov', $CodigoProveedorFiltro);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getAllDocumentosNotRemovedByMasterStep($MasterStepArray){
        $list = $this->createQueryBuilder('n')
            ->andWhere('n.master_step_id in (:masters)')
            ->andWhere('n.status_id != 3')
            ->join("n.instancia_workflow", "iw")
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->andWhere('iw.status not in (20)')
            ->andWhere('iw.id >= 1000')
            ->andWhere('iw.id <= 4000')
            ->setParameter('masters', $MasterStepArray)
            ->orderBy('n.id', 'ASC');

        $query = $list->getQuery();

        return $query->getResult();

    }

    public function search($type,$filters)
    {
        $em = $this->getEntityManager();

        if(!empty($filters)){
            if (isset($filters["user"])) {
                $user = $filters["user"];
            }
        }

        switch($type){
            case "list":
                $list = $this->createQueryBuilder('s')
                    ->select('s.id as id_grid','i.id', 'i.usercreatedid','mw.name','ms.name as name2','u.name as creator','i.created','m.modified','m.lote','m.material','m.equipo','m.workordersap','mw.logbook','i.status','s.id as step','i.in_edition','mw.logbook','us.id as idNextSigner','r.registro_viejo_id as id_reconciliado','r2.registro_nuevo_id as id_reconciliado_sig','mw.checklist as tiene_checklist','ms.checklist as es_checklist','s.dependsOn');
                $list->addSelect("CASE WHEN (((SELECT COUNT(ela.step_id) FROM Nononsense\HomeBundle\Entity\FirmasStep ela WHERE ela.userEntiy=:el_user AND ela.step_id=s.id AND (ela.elaboracion=1 OR (ela.accion LIKE 'Cancelado en verificación:%' AND i.status=14)))>0 OR i.usercreatedid=:el_user_id) AND NOT (i.status=14 AND f.accion LIKE 'Cancelado en verificación:%' AND f.userEntiy!=:user_cancel)) THEN 0 ELSE 1 AS validate");
                $list->addSelect("CASE WHEN ((SELECT COUNT(elac.step_id) FROM Nononsense\HomeBundle\Entity\FirmasStep elac WHERE elac.userEntiy=:el_userc AND elac.step_id=s.id AND elac.elaboracion=0)>0) THEN 0 ELSE 1 AS cumpliment");
                $list->setParameter('el_user', $user);
                $list->setParameter('user_cancel', $user);
                $list->setParameter('el_userc', $user);
                $list->setParameter('el_user_id', $user->getId());

                break;
            case "count":
                $list = $this->createQueryBuilder('s')
                    ->select('COUNT(s.id) as conta');
                break;
        }

        $list->leftJoin("s.instancia_workflow", "i")
            ->leftJoin("s.master_step", "ms")
            ->leftJoin("i.Master_Workflow_Entity", "mw")
            ->leftJoin("mw.category", "c")
            ->leftJoin("i.userCreatedEntiy", "u")
            ->leftJoin("i.metaData", "m")
            ->leftJoin("s.firmasStep", "f")
            ->leftJoin("f.userEntiy", "us")
            ->leftJoin("i.ReconciliadoDe","r","WITH", 'r.status>0')
            ->leftJoin("i.ReconciliadoA","r2","WITH", 'r2.status>0')
            ->andWhere('s.status_id>=0')
            ->andWhere('i.status>=0')
            ->andWhere('ms.dependsOn=0 OR (ms.dependsOn > 0 AND (i.status = 6 or i.status = 4 or i.status = 7 or  i.status = 12 or i.status = 13 or i.status = 15 or i.status = 9 or i.status = 10))')
            ->andWhere('f.id IS NULL OR f.id = (SELECT MAX(aux.id) FROM Nononsense\HomeBundle\Entity\FirmasStep aux WHERE aux.step_id=f.step_id)')
            ->orderBy('s.workflow_id', 'DESC')
            ->addOrderBy('s.dependsOn', 'ASC');



        if(!empty($filters)){

            if(isset($filters["id"])){
                $list->andWhere('s.id=:id OR s.dependsOn=:dependOn');
                $list->setParameter('id', $filters["id"]);
                $list->setParameter('dependOn', $filters["id"]);
            }

            if(isset($filters["master_step_id"])){
                $list->andWhere('s.master_step_id=:master_step_id');
                $list->setParameter('master_step_id', $filters["master_step_id"]);
            }

            

            if(isset($filters["plantilla_id"])){
                $list->andWhere('ms.plantilla_id=:plantilla_id');
                $list->setParameter('plantilla_id', $filters["plantilla_id"]);
            }

            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('mw.name LIKE :name'.$key);
                    $list->orWhere('ms.name LIKE :name2'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                    $list->setParameter('name2'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["creator"])){
                $terms = explode(" ", $filters["creator"]);
                foreach($terms as $key => $term){
                    $list->andWhere('u.name LIKE :creator'.$key);
                    $list->setParameter('creator'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["content"])){
                $terms = explode(" ", $filters["content"]);
                foreach($terms as $key => $term){
                    $list->andWhere('s.stepDataValue LIKE :content'.$key);
                    $list->setParameter('content'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["lot"])){
                $list->andWhere('m.lote=:lot');
                $list->setParameter('lot', $filters["lot"]);
            }

            if(isset($filters["material"])){
                $list->andWhere('m.material=:material');
                $list->setParameter('material', $filters["material"]);
            }

            if(isset($filters["equipment_number"])){
                $list->andWhere('m.equipo=:equipment_number');
                $list->setParameter('equipment_number', $filters["equipment_number"]);
            }

            if(isset($filters["sap"])){
                $list->andWhere('m.workordersap=:sap');
                $list->setParameter('sap', $filters["sap"]);
            }

            if(isset($filters["fll"]) && $filters["fll"]=="1"){
                $fll=1;
            }
            else{
                $fll=0;
            }

            if(isset($filters["status"])){
                switch($filters["status"]){
                    case 1:
                        $list->andWhere('i.status=0 OR i.status=1 OR i.status=2 OR i.status=3');
                        break;
                    case 2:
                        $list->andWhere('i.status=5');
                        break;
                    case 3:
                        $list->andWhere('i.status=6');
                        break;
                    case 4:
                        $list->andWhere('i.status=4 OR i.status=15 OR i.status=12 OR i.status=7 or i.status=13');
                        break;
                    case 5:
                        $list->andWhere('i.status=14');
                        break;
                    case 6:
                        $list->andWhere('i.status=8');
                        break;
                    case 7:
                        $list->andWhere('i.status=9');
                        break;
                    case 8:
                        $list->andWhere('i.status=10');
                        break;
                    case 9:
                        $list->andWhere('i.status=11');
                        break;
                }

            }

            if(isset($filters["destruction"])){
                $list->andWhere('i.status=6 OR i.status=8 OR i.status=9 OR i.status=10');

            }

            if (isset($filters["pending_for_me"])) {
                $list->andWhere('(i.status IN (1,2,3,7,12,13,15) AND us.id=:user_id AND f.status=0) 
                    OR (
                        i.status IN (4,5)
                        AND s.id NOT IN (SELECT el.step_id FROM Nononsense\HomeBundle\Entity\FirmasStep el WHERE el.userEntiy=:el_user_aux AND el.step_id=s.id AND  (el.elaboracion=1 OR (el.accion LIKE :return_verify AND i.status=14)))
                        AND i.usercreatedid!=:user_id2) 
                    OR (i.status=14 AND f.accion LIKE :return_verify_aux AND f.userEntiy!=:user_cancel_aux)
                    OR (
                        i.status=0 AND s.id NOT IN (SELECT elc.step_id FROM Nononsense\HomeBundle\Entity\FirmasStep elc WHERE elc.userEntiy=:el_user_auxc AND elc.step_id=s.id AND elc.elaboracion=0))');


                $list->setParameter('user_id', $user->getId());
                $list->setParameter('user_id2', $user->getId());
                $list->setParameter('el_user_aux', $user);
                $list->setParameter('user_cancel_aux', $user);
                $list->setParameter('el_user_auxc', $user);
                $list->setParameter('return_verify', 'Cancelado en verificación:%');
                $list->setParameter('return_verify_aux', 'Cancelado en verificación:%');
            }


            if(isset($filters["from"])){
                $list->andWhere('i.created>=:from');
                $list->setParameter('from', $filters["from"]);
            }

            if(isset($filters["until"])){
                $list->andWhere('i.created<=:until');
                $list->setParameter('until', $filters["until"]." 23:59:00");
            }
        }


        if(isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();


        switch($type){
            case "list":
                return $query->getResult();
                break;
            case "count":
                return $query->getSingleResult()["conta"];
                break;
        }
    }

}
