<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Instancias_WorkflowsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanciasWorkflowsRepository extends EntityRepository
{
    /**
     * List of Instancias_Workflows with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listInstancias_Workflows($page = 1, $max = 10, $sort = 'id', $query = 'q', $user_id = 3)
    {
        $list = $this->createQueryBuilder('n')
            ->join("n.Master_Workflow_Entity", "mw")
            ->join("n.userCreatedEntiy", "uc")
            ->select('n.id, n.master_workflow, n.description, n.isActive', 'n.created', 'n.status', 'mw.name as type', 'n.masterDataValues', 'n.signvalues', 'uc.name as usercreatedname', 'uc.id as usercreatedid')
            ->andWhere('n.status < 20')
            ->andWhere('(n.usercreatedid = :userid) or (n.userLogisticaColaboratedEntiy = :userid)')
            ->setParameter('userid', '' . $user_id . '');

        $list->orderBy('n.' . $sort, 'DESC');

        //$list->setFirstResult(($page-1) * $max);
        //$list->setMaxResults($max);

        $paginator = new Paginator($list);
        //this is a hack to be able to choose some certain fields
        $paginator->setUseOutputWalkers(false);

        return $paginator;
    }


    public function reportingInstancias_Workflows($page = 1, $max = 10, $sort = 'id', $userCreated = '', $idInput, $idCodProv, $idProv, $idEstado, $idPlantillas, $idAnyo, $idJefeProd, $idTipoProd, $idCIF, $idSecc)
    {
        $list = $this->createQueryBuilder('n')
            //->andWhere('n.usercreatedid != 3')
            //->andWhere('n.usercreatedid != 22')
            ->andWhere('n.status != 20')
            ->andWhere('n.usercreatedid not in (0,1,2,23,30,31,32,34,35,347,346,343,373)');

        if ($idInput != "") {
            $list->andWhere('n.id = :idworkflow');
            $list->setParameter('idworkflow', $idInput);
        }

        if ($userCreated != "") {
            $list->andWhere('n.usercreatedid = :user');
            $list->setParameter('user', $userCreated);
        }

        if ($idPlantillas != "") {
            $list->andWhere('n.master_workflow = :mw');
            $list->setParameter('mw', $idPlantillas);
        }


        if ($idAnyo != "") {
            $list->andWhere('n.year = :year');
            $list->setParameter('year', $idAnyo);
        }

        if ($idEstado != "") {
            $list->andWhere('n.status = :st');
            $list->setParameter('st', $idEstado);
        }
        /*
                $leftJoinMetaData = false;
                if ($idCodProv != "") {
                    $leftJoinMetaData = true;
                    $list->leftJoin("n.metaData", "metadata");
                    $list->andWhere('metadata.codigo_proveedor = :codprov');
                    $list->setParameter('codprov', $idCodProv);
                }

                if ($idSecc != "") {
                    //seccion_id
                    if (!$leftJoinMetaData) {
                        $leftJoinMetaData = true;

                        $list->leftJoin("n.metaData", "metadata");
                        $list->andWhere('metadata.seccion_id = :seccionid');
                        $list->setParameter('seccionid', $idSecc);
                    }
                }

                if($idTipoProd != ""){
                    if (!$leftJoinMetaData) {
                        $list->leftJoin("n.metaData", "metadata");
                    }

                    if($idTipoProd == 0){
                        // MN
                        $list->andWhere('metadata.MN = 1');
                    }
                    if($idTipoProd == 1){
                        // MP
                        $list->andWhere('metadata.MP = 1');

                    }
                    if($idTipoProd == 2){
                        // PP
                        $list->andWhere('metadata.PP = 1');

                    }

                }
        */
        if ($idJefeProd != "") {
            $list->leftJoin("n.metaFirmantes", "metafirmantes");
            $list->andWhere('metafirmantes.name like :nameccc');
            $list->setParameter('nameccc', '%' . $idJefeProd . '%');


        }


        $list->orderBy('n.' . $sort, 'DESC');

        if ($page != "") {
            $list->setFirstResult(($page - 1) * $max);
            $list->setMaxResults($max);
        }

        $paginator = new Paginator($list);
        //this is a hack to be able to choose some certain fields
        $paginator->setUseOutputWalkers(false);

        return $paginator;
    }


    public function listArchivo($user_logged, $usuario, $nRegistro, $nombrePlantilla, $SAP, $equipo, $lote, $material, $nWorkflow, $estado, $fechaInicio, $fechaFin)
    {
        $list = $this->createQueryBuilder('n')
            ->select('n.id', 'ms.name', 'ms.description', 'c.name as companyName', 'n.status', 'u.name as namecreated')
            ->leftJoin("n.Master_Workflow_Entity", "ms")
            ->leftJoin("ms.category", "c")
            ->leftJoin("n.userCreatedEntiy", "u")
            ->andWhere('n.status in (6,8,9,10)')
//            ->andWhere('n.usercreatedid = :user')
            //          ->setParameter('user',$user_logged)
            ->orderBy('n.id', 'DESC');

        if ($usuario != "") {
            $list->andWhere('u.name LIKE :username');
            $list->setParameter('username', '%' . $usuario . '%');
        }
        if ($nRegistro != "") {
            $list->andWhere('n.id = :idRegistro');
            $list->setParameter('idRegistro', $nRegistro);
        }
        if ($nombrePlantilla != "") {
            $list->andWhere('ms.name LIKE :plantillaname');
            $list->setParameter('plantillaname', '%' . $nombrePlantilla . '%');
        }

        if ($nWorkflow != "") {
            $list->andWhere('ms.id= :idmasterworkflow');
            $list->setParameter('idmasterworkflow', $nWorkflow);
        }

        if ($estado != 0) {
            $list->andWhere('n.status = :estado');
            $list->setParameter('estado', $estado);
        }

        if ($fechaInicio != "") {
            $list->andWhere('n.created >= :inicio');
            $list->setParameter('inicio', $fechaInicio);
        }

        if ($fechaFin != "") {
            $list->andWhere('n.created <= :fin');
            $list->setParameter('fin', $fechaFin);
        }

        $leftJoinMetaData = false;
        if ($SAP != "") {
            $leftJoinMetaData = true;
            $list->leftJoin("n.metaData", "metadata");
            $list->andWhere('metadata.workordersap = :workordersap');
            $list->setParameter('workordersap', $SAP);
        }

        if ($equipo != "") {
            if (!$leftJoinMetaData) {
                $leftJoinMetaData = true;
                $list->leftJoin("n.metaData", "metadata");
            }
            $list->andWhere('metadata.equipo = :equipo');
            $list->setParameter('equipo', $equipo);
        }

        if ($lote != "") {
            if (!$leftJoinMetaData) {
                $leftJoinMetaData = true;
                $list->leftJoin("n.metaData", "metadata");
            }
            $list->andWhere('metadata.lote = :lote');
            $list->setParameter('lote', $lote);
        }

        if ($material != "") {
            if (!$leftJoinMetaData) {
                $leftJoinMetaData = true;
                $list->leftJoin("n.metaData", "metadata");
            }
            $list->andWhere('metadata.material = :material');
            $list->setParameter('material', $material);
        }


        $query = $list->getQuery();

        return $query->getResult();
    }

    public function listProcess($user_logged)
    {
        $list = $this->createQueryBuilder('n')
            ->select('n.id', 'ms.name', 'ms.description', 'c.name as companyName', 'n.status', 'mt.fechainicio as fecha', 'n.in_edition', 'ms.id as masterworkflowid', 'ms.logbook')
            ->leftJoin("n.Master_Workflow_Entity", "ms")
            ->leftJoin("ms.category", "c")
            ->innerJoin("n.metaData", "mt")
            ->andWhere('n.status in (0,1,2,3,5,4,16,11,17)')
            ->andWhere('n.usercreatedid = :user')
            ->setParameter('user', $user_logged)
            ->orderBy('n.id', 'DESC');

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function listStandBy($status)
    {
        $list = $this->createQueryBuilder('n')
            ->select('n.id', 'ms.name', 'ms.description', 'c.name as companyName', 'n.status', 'mt.fechainicio as fecha', 'n.in_edition', 'ms.id as masterworkflowid', 'ms.logbook')
            ->leftJoin("n.Master_Workflow_Entity", "ms")
            ->leftJoin("ms.category", "c")
            ->innerJoin("n.metaData", "mt")
            ->andWhere('n.status in (:stst)')
            ->setParameter('stst', $status)
            ->orderBy('n.id', 'DESC');

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function listProcessParcial($page, $max, $idregistro, $idcodigomaterial, $idlote, $idcodigoequipo, $idworkordersap, $idcodigodocumento)
    {
        $list = $this->createQueryBuilder('n')
//            ->select('n.id as id', 'ms.name', 'ms.description', 'c.name as companyName', 'n.status', 'mt.fechainicio as fecha')
            ->select('n.id', 'ms.name', 'ms.description','ms.name as masterWorkflowName', 'c.name as companyName', 'n.status', 'mt.fechainicio as fecha', 'n.in_edition', 'ms.id as masterworkflowid', 'ms.logbook')
            ->leftJoin("n.Master_Workflow_Entity", "ms")
            ->leftJoin("ms.category", "c")
            ->leftJoin("n.metaData", "mt")
            ->andWhere('n.status in (0,1,2,3,5,4,16)')
            ->orderBy('n.id', 'DESC');

        if ($idregistro != "-1") {
            $list->andWhere('n.id = :iden');
            $list->setParameter('iden', $idregistro);
        }

        if ($idcodigomaterial != -1) {

            $list->andWhere('mt.material = :iducodigomaterial');
            $list->setParameter('iducodigomaterial', $idcodigomaterial);
        }
        if ($idlote != -1) {

            $list->andWhere('mt.lote = :idlote');
            $list->setParameter('idlote', $idlote);
        }
        if ($idcodigoequipo != -1) {

            $list->andWhere('mt.equipo = :idcodigoequipo ');
            $list->setParameter('idcodigoequipo', $idcodigoequipo);
        }
        if ($idworkordersap != -1) {

            $list->andWhere('mt.workordersap = :idworkorder ');
            $list->setParameter('idworkorder', $idworkordersap);
        }
        if ($idcodigodocumento != -1) {

            $list->andWhere('mt.codigo_documento_lote = :iddocumentolote ');
            $list->setParameter('iddocumentolote', $idcodigodocumento);
        }

        $list->setFirstResult(($page - 1) * $max);
        $list->setMaxResults($max);

        $query = $list->getQuery();
        return $query->getResult();
        //return new Paginator($list);
    }


    public function getAllInstanciasWorkflowNotRemovedByMasterWorkflow($MasterWorkflowArray)
    {
        $list = $this->createQueryBuilder('n')
            ->andWhere('n.status != 20')
            ->andWhere('n.usercreatedid != 3')
            ->andWhere('n.usercreatedid != 22')
            ->andWhere('n.usercreatedid not in (0,1,2,23,30,31,32,34,35,347,346,343,373)')
            ->orderBy('n.id', 'ASC');

        $list->andWhere('n.master_workflow in (:mw)');
        $list->setParameter('mw', $MasterWorkflowArray);

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getAllInstanciasWorkflowNotRemoved()
    {
        $list = $this->createQueryBuilder('n')
            ->andWhere('n.status != 20')
            //          ->andWhere('n.id >= 2421')
//            ->andWhere('n.id <= 4921')
            ->orderBy('n.id', 'ASC');

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getAllInstanciasWorkflowNotRemovedById($id)
    {
        $list = $this->createQueryBuilder('n')
            ->andWhere('n.status != 20')
            //          ->andWhere('n.id >= 2421')
//            ->andWhere('n.id <= 4921')
            ->orderBy('n.id', 'ASC');

        $list->andWhere('n.id in (:ids)');
        $list->setParameter('ids', $id);

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function listValidacionesPendientes($user_logged, $arrayGroupsUser)
    {

        $list = $this->createQueryBuilder('n')
            ->select('ms.name', 'ms.description', 'c.name as companyName', 'n.id as registroid', 'mt.fechainicio as fecha', 'mt.lote', 'mt.material as codigo', 'u.name as namecreated', 'n.in_edition', 'ms.checklist as checklist', 'n.status', 'ms.id as masterworkflowid')
            ->leftJoin("n.Master_Workflow_Entity", "ms")
            ->leftJoin("ms.category", "c")
            ->leftJoin("n.userCreatedEntiy", "u")
            ->innerJoin("n.metaData", "mt")
            ->andWhere('n.status in (5,4,14,7,12,13,15)')
            ->andWhere('n.usercreatedid != :user')
            ->andWhere('ms.group_id in (:groupsuser)')
            ->setParameter('user', $user_logged)
            ->setParameter('groupsuser', $arrayGroupsUser)
            ->orderBy('n.id', 'DESC');


        $query = $list->getQuery();

        return $query->getResult();

    }
    public function search($type,$filters)
    {
        $em = $this->getEntityManager();

        if(!empty($filters)){
            if (isset($filters["user"])) {
                $user = $filters["user"];
            }
        }

        switch($type){
            case "list":
                $list = $this->createQueryBuilder('i')
                    ->select('i.id', 'i.usercreatedid','mw.name','u.name as creator','i.created','m.modified','m.lote','m.material','m.equipo','m.workordersap','mw.logbook','i.status','s.id as step','i.in_edition','mw.logbook','us.id as idNextSigner','r.registro_viejo_id as id_reconciliado','mw.checklist as checklist','ch.id as chstep','ms.name as chname');
                $list->addSelect("CASE  WHEN (SELECT COUNT(ela.step_id) FROM Nononsense\HomeBundle\Entity\FirmasStep ela WHERE ela.userEntiy=:el_user AND ela.step_id=s.id AND ela.elaboracion=1)>0 THEN 0 ELSE 1 AS validate");
                $list->setParameter('el_user', $user);

                break;
            case "count":
                $list = $this->createQueryBuilder('i')
                    ->select('COUNT(i.id) as conta');
                break;
        }

        $list->leftJoin("i.Master_Workflow_Entity", "mw")
            ->leftJoin("mw.category", "c")
            ->leftJoin("i.userCreatedEntiy", "u")
            ->leftJoin("i.metaData", "m")
            ->leftJoin("i.Steps", "s", "WITH", 's.dependsOn=0')
            ->leftJoin("i.Steps", "ch", "WITH", 'ch.dependsOn=s.id')
            ->leftJoin("ch.master_step", "ms", "WITH", 'ms.checklist=1')
            ->leftJoin("s.firmasStep", "f")
            ->leftJoin("f.userEntiy", "us")
            ->leftJoin("i.ReconciliadoDe","r")
            ->andWhere('i.status>=0')
            ->andWhere('f.id IS NULL OR f.id IN (SELECT MAX(aux.id) FROM Nononsense\HomeBundle\Entity\FirmasStep aux WHERE aux.step_id=f.step_id)')
            ->orderBy('i.id', 'DESC');



        if(!empty($filters)){

            if(isset($filters["id"])){
                $list->andWhere('i.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["plantilla_id"])){
                $list->andWhere('mw.id IN (SELECT ms.workflow_id FROM Nononsense\HomeBundle\Entity\MasterSteps ms WHERE  ms.plantilla_id=:plantilla_id)');
                $list->setParameter('plantilla_id', $filters["plantilla_id"]);
            }

            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('mw.name LIKE :name'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["creator"])){
                $terms = explode(" ", $filters["creator"]);
                foreach($terms as $key => $term){
                    $list->andWhere('u.name LIKE :creator'.$key);
                    $list->setParameter('creator'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["content"])){
                $terms = explode(" ", $filters["content"]);
                foreach($terms as $key => $term){
                    $list->andWhere('s.stepDataValue LIKE :content'.$key);
                    $list->setParameter('content'.$key, '%' . $term. '%');
                }
            }

            if(isset($filters["lot"])){
                $list->andWhere('m.lote=:lot');
                $list->setParameter('lot', $filters["lot"]);
            }

            if(isset($filters["material"])){
                $list->andWhere('m.material=:material');
                $list->setParameter('material', $filters["material"]);
            }

            if(isset($filters["equipment_number"])){
                $list->andWhere('m.equipo=:equipment_number');
                $list->setParameter('equipment_number', $filters["equipment_number"]);
            }

            if(isset($filters["sap"])){
                $list->andWhere('m.workordersap=:sap');
                $list->setParameter('sap', $filters["sap"]);
            }

            if(isset($filters["status"])){
                switch($filters["status"]){
                    case 1:
                        $list->andWhere('i.status=0 OR i.status=1 OR i.status=2 OR i.status=3');
                        break;
                    case 2:
                        $list->andWhere('i.status=5');
                        break;
                    case 3:
                        $list->andWhere('i.status=6');
                        break;
                    case 4:
                        $list->andWhere('i.status=4 OR i.status=15 OR i.status=12 OR i.status=7 or i.status=13');
                        break;
                    case 5:
                        $list->andWhere('i.status=14');
                        break;
                    case 6:
                        $list->andWhere('i.status=8');
                        break;
                    case 7:
                        $list->andWhere('i.status=9');
                        break;
                    case 8:
                        $list->andWhere('i.status=10');
                        break;
                    case 9:
                        $list->andWhere('i.status=11');
                        break;
                }

            }

            if (isset($filters["pending_for_me"])) {
                $list->andWhere('(i.status IN (1,2,3,7,12,13,15) AND us.id=:user_id) OR (i.status IN (4,5,14) AND s.id NOT IN (SELECT el.step_id FROM Nononsense\HomeBundle\Entity\FirmasStep el WHERE el.userEntiy=:el_user_aux AND el.step_id=s.id AND el.elaboracion=1)) OR i.status=0');
                $list->setParameter('user_id', $user->getId());
                $list->setParameter('el_user_aux', $user);
            }


            if(isset($filters["from"])){
                $list->andWhere('i.created>=:from');
                $list->setParameter('from', $filters["from"]);
            }

            if(isset($filters["until"])){
                $list->andWhere('i.created<=:until');
                $list->setParameter('until', $filters["until"]." 23:59:00");
            }
        }


        if(isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();


        switch($type){
            case "list":
                return $query->getResult();
                break;
            case "count":
                return $query->getSingleResult()["conta"];
                break;
        }
    }


}


