<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstanciasStepsHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanciasStepsHistoryRepository extends EntityRepository
{
	public function list($filters)
	{
		$list = $this->createQueryBuilder('ish')
            	->join("ish.evidencia", "e")
            	->join("e.stepEntity", "s")
            	->join("e.userEntiy", "u")
            	->join("s.master_step", "ms");


        if(isset($filters["content"])){
            $terms = explode(" ", $filters["content"]);
            foreach($terms as $key => $term){
                $list->andWhere('e.stepDataValue LIKE :content_'.$key);
                $list->setParameter('content_'.$key, '%'.$term.'%');
            }
        }

        if (isset($filters['field'])) {
        	$list->andWhere('ish.field = :field');
        	$list->setParameter('field', $filters['field']);
        }

        if (isset($filters['index'])) {
        	$list->andWhere('ish.index = :index');
        	$list->setParameter('index', $filters['index']);
        }

        if (isset($filters['value'])) {
        	$list->andWhere('ish.value = :value');
        	$list->setParameter('value', $filters['value']);
        }

        if (isset($filters['creator'])) {
        	$list->andWhere('u.username = :username');
        	$list->orWhere('u.email = :username');
        	$list->setParameter('username', $filters['creator']);
        }

        if (isset($filters['name'])) {
        	$list->andWhere('ms.name LIKE :name');
        	$list->setParameter('name', '%'.$filters['name'].'%');
        }

        if (isset($filters['id'])) {
        	$list->andWhere('s.id = :id');
        	$list->setParameter('id', $filters['id']);
        }

        $query = $list->getQuery();

        return $query->getResult();
	}
}
