<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Instancias_StepsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanciasStepsRepository extends EntityRepository
{
    /**
     * List of Instancias_Steps with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listInstanciasSteps($sort = 'position', $id = '0')
    {
        $list = $this->createQueryBuilder('n')
            ->join('n.master_step', 'ms')
            ->select('n.id, n.workflow_id, n.master_step_id, n.isActive, n.dependsOn, n.rules, n.notification, n.status_id, n.modified, n.usage_id, n.token, ms.name','ms.plantilla_id','ms.cloneable','ms.block','ms.optional')
            ->andWhere('n.workflow_id = :id')
            ->setParameter('id', '' . $id . '');


        $list->orderBy('ms.' . $sort, 'ASC');


        $paginator = new Paginator($list);
        //this is a hack to be able to choose some certain fields
        $paginator->setUseOutputWalkers(false);

        return $paginator;
    }

    /**
     * Counts the total number of news
     *
     * @return int
     */
    public function countTotal()
    {
        $qb = $this->createQueryBuilder('n');
        $qb->select('COUNT(n)');

        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }

    /**
     * List of Instancias_Steps completed by workflow id ordered by position
     *
     * @param int $workflowid
     * @param int $status_id
     * @param string $sort
     * @return Paginator
     */
    public function listInstanciasStepsByWorkflowIdAndStatus($workflowid = '1', $status_id = '4',$sort = 'position')
    {
        $list = $this->createQueryBuilder('n')
            ->join('n.master_step', 'ms')
            ->select('n.id, n.workflow_id, n.master_step_id, n.isActive, n.dependsOn, n.rules, n.notification, n.status_id, n.modified, n.usage_id, n.token, ms.name','ms.plantilla_id','ms.cloneable','ms.block','ms.optional')
            ->andWhere('n.workflow_id = :id and n.status_id = :status')
            //->setParameter('id', '' . $workflowid . '')
            ->setParameter('status', '' . $status_id . '')
            ->orderBy('ms.' . $sort, 'ASC');



        $paginator = new Paginator($list);

        return $paginator;
    }

    public function getProteccionStock($dateString){
        $list = $this->createQueryBuilder('n')
            ->select('n.id')
            ->andWhere('n.master_step_id = 160')
            ->join("n.instancia_workflow", "iw")
            ->andWhere('n.status_id not in (:status)')
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->andWhere('iw.created = :create')
            ->setParameter('status', array(0,3))
            ->setParameter('create', $dateString)
            ->orderBy('n.id', 'ASC');


        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getProteccionStockTotal(){
        $list = $this->createQueryBuilder('n')
            ->select('n.id','metadata.codigo_proveedor')
            ->andWhere('n.master_step_id = 160')
            ->join("n.instancia_workflow", "iw")
            ->leftJoin("iw.metaData", "metadata")
            ->andWhere("iw.description like '%Protección de Stock%' ")
            ->andWhere('iw.status != 20')
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->orderBy('n.id', 'ASC');


        $query = $list->getQuery();

        return $query->getResult();
    }


    public function getMargenStock($dateString){
        $list = $this->createQueryBuilder('n')
            ->select('n.id')
            ->andWhere('n.master_step_id = 159')
            ->join("n.instancia_workflow", "iw")
            ->andWhere('n.status_id not in (:status)')
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->andWhere('iw.created = :create')
            ->setParameter('status', array(0,3))
            ->setParameter('create', $dateString)
            ->orderBy('n.id', 'ASC');


        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getInstanciasStepsDescuentoLogistico($CifProveedor, $arrayAnyosFiltro, $arrayPlantillasFiltro, $fechaDesde, $fechaHasta, $arrayEstadosFiltro,$arrayFlujosFiltro,$CodigoProveedorFiltro,$NameProv){

        /*

            ->andWhere('n.usercreatedid != 22')
            //->andWhere('iw.status not in (0,3,8,20)')
            ->andWhere('iw.status not in (20)')
         */
        $list = $this->createQueryBuilder('n')
            ->andWhere('n.master_step_id in (:flujos)')
            ->join("n.instancia_workflow", "iw")
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->andWhere('iw.status not in (0,3,8,20)')
            ->setParameter('flujos', $arrayFlujosFiltro)
            ->orderBy('n.id', 'ASC');

        $list->andWhere('iw.year in (:year)');
        $list->setParameter('year', $arrayAnyosFiltro);


        $list->andWhere('iw.master_workflow in (:mw)');
        $list->setParameter('mw', $arrayPlantillasFiltro);

        $list->andWhere('iw.status in (:st)');
        $list->setParameter('st', $arrayEstadosFiltro);

        if ($fechaDesde != "") {
            $list->andWhere('iw.modified = :desde');
            $list->setParameter('desde', $fechaDesde);
        }
        if ($fechaHasta != "") {
            $list->andWhere('iw.modified = :hasta');
            $list->setParameter('hasta', $fechaHasta);
        }



        if ($CodigoProveedorFiltro != "") {
            $leftJoinMetaData = true;
            $list->leftJoin("iw.metaData", "metadata");
            $list->andWhere('metadata.codigo_proveedor = :codprov');
            $list->setParameter('codprov', $CodigoProveedorFiltro);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function getAllDocumentosNotRemovedByMasterStep($MasterStepArray){
        $list = $this->createQueryBuilder('n')
            ->andWhere('n.master_step_id in (:masters)')
            ->andWhere('n.status_id != 3')
            ->join("n.instancia_workflow", "iw")
            ->andWhere('iw.usercreatedid not in (0,1,2,3,22,23,30,31,32,34,35,347,346,343,373)')
            ->andWhere('iw.status not in (20)')
            ->andWhere('iw.id >= 1000')
            ->andWhere('iw.id <= 4000')
            ->setParameter('masters', $MasterStepArray)
            ->orderBy('n.id', 'ASC');

        $query = $list->getQuery();

        return $query->getResult();

    }

}
