<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Master_WorkflowsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterWorkflowsRepository extends EntityRepository
{

    /**
     * List of Master_Workflows with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listInstancias_Workflows($page = 1, $max = 10, $sort = 'id')
    {
        $list = $this->createQueryBuilder('n')
            ->select('n.id, n.name', 'n.description', 'n.isActive');

        $list->orderBy('n.' . $sort, 'DESC');

        $list->setFirstResult(($page - 1) * $max);
        $list->setMaxResults($max);

        $paginator = new Paginator($list);
        //this is a hack to be able to choose some certain fields
        $paginator->setUseOutputWalkers(false);

        return $paginator;
    }

    public function listDocumentosByNameAndCategory($name, $categories)
    {
        $list = $this->createQueryBuilder('n')
            ->select('n.id', 'n.name', 'n.description', 'c.name as subCatName', 'c.padre as padre', 'n.logbook')
            ->leftJoin("n.category", "c")
            ->andWhere('n.isActive = 1')
            ->orderBy('n.id', 'ASC');

        if ($name != "") {
            $list->andWhere('n.name like :nameDocumento');
            $list->setParameter('nameDocumento', '%' . $name . '%');
        }

        if (!empty($categories)) {
            $list->andWhere('n.category_id in (:categories)');
            $list->setParameter('categories', $categories);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function detail($id)
    {
        $list = $this->createQueryBuilder('n')
            ->select('n.id', 'n.name', 'n.description', 'c.id as subcategoryId', 'c.padre as categoryId', 'n.logbook', 'n.isActive','n.checklist','s.plantilla_id','s.id stepId','n.precreation')
            ->leftJoin("n.category", "c")
            ->leftJoin("n.MasterSteps", "s", "WITH", 's.dependsOn=0')
            ->andWhere('n.isActive = 1');

        if ($id != "") {
            $list->andWhere('n.id=:id');
            $list->setParameter('id', $id);
        }

        $query = $list->getQuery();

        return $query->getOneOrNullResult();
    }
}
