<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * Master_StepsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterStepsRepository extends EntityRepository
{
    /**
     * List of Master_Steps with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listMasterSteps($idmasterworkflow = '0')
    {
        $list = $this->createQueryBuilder('n')
            ->select('n.id, n.dependsOn')
            ->andWhere('n.workflow_id = :id')
            ->setParameter('id', '' . $idmasterworkflow . '');


        $list->orderBy('n.id' , 'ASC');


        $paginator = new Paginator($list);
        //this is a hack to be able to choose some certain fields
        $paginator->setUseOutputWalkers(false);

        return $paginator;
    }



}
