<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\QueryBuilder;

/**
 * MaterialCleanCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialCleanCodesRepository extends EntityRepository
{

    /**
     * @param array $filters
     * @param int $paginate
     * @return array|int|string
     */
    public function list($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('mcc')
            ->select('mcc.id', 'mcc.code', 'm.name as material', 'c.name as center' )
            ->innerJoin('mcc.idMaterial','m')
            ->innerJoin('mcc.idCenter','c')
            ->orderBy('mcc.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    /**
     * @param array $filters
     * @return mixed
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function count($filters = array())
    {
        $list = $this->createQueryBuilder('mcc')
            ->select('COUNT(mcc.id) as conta')
            ->innerJoin('mcc.idMaterial','m')
            ->innerJoin('mcc.idCenter','c');

        $list = self::fillFilersQuery($filters, $list);

        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }

    /**
     * @param array $filters
     * @param QueryBuilder $list
     * @return QueryBuilder
     */
    private function fillFilersQuery($filters, $list){

        if(!empty($filters)){
            if(isset($filters["center"])){
                $list->andWhere('c.id = :center');
                $list->setParameter('center', $filters["center"]);
            }
            if(isset($filters["material"])){
                $list->andWhere('m.id = :material');
                $list->setParameter('material', $filters["material"]);
            }
            if(isset($filters["code"])){
                $list->andWhere('mcc.code like :code');
                $list->setParameter('code', '%' . $filters["code"] . '%');
            }
        }

        return $list;
    }

}
