<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaterialCleanCleansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialCleanCleansRepository extends EntityRepository
{
    public const status = [
        1 => 'Material limpio',
        2 => 'Verificado limpieza',
        3 => 'Matierial sucio',
        4 => 'Revisado'
    ];

    /**
     * @param int $status
     * @return string
     */
    public function getStatusName($status)
    {
        if(isset(self::status[$status])){
            return self::status[$status];
        }
        return 'Desconocido';
    }
}
