<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaterialCleanCentersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialCleanCentersRepository extends EntityRepository
{

    public function list($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('c')
            ->select('c')
            ->orderBy('c.name', 'ASC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $list = $this->createQueryBuilder('c')
            ->select('COUNT(c.id) as conta');

        $list = self::fillFilersQuery($filters, $list);

        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }

    private function fillFilersQuery($filters, $list){

        if(!empty($filters)){
            if(isset($filters["name"])){
                $list->andWhere("c.name LIKE '%".$filters["name"]."%'");
            }
        }

        return $list;
    }

}
