<?php
/**
 * Created by IntelliJ IDEA.
 * User: gushe
 * Date: 23/09/2019
 * Time: 8:43
 */

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PesasQRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PesasQRRepository extends EntityRepository
{

}