<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsOutputsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsOutputsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('po')
            ->select('po')
            ->innerJoin("po.productInput", "pi")
            ->innerJoin("pi.product", "p")
            ->innerJoin("p.type", "t")
            ->orderBy('po.date', 'DESC');
        $list = self::fillFilersQuery($filters, $list);
        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }
        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $list = $this->createQueryBuilder('po')
            ->select('COUNT(po.id) as conta')
            ->innerJoin("po.productInput", "pi")
            ->innerJoin("pi.product", "p")
            ->innerJoin("p.type", "t");
        $list = self::fillFilersQuery($filters, $list);
        $query = $list->getQuery();
        return $query->getSingleResult()["conta"];
    }

    private function fillFilersQuery($filters, $list){
    	if(!empty($filters)){
        	if(isset($filters["partNumber"])){
                $list->andWhere('p.partNumber=:partNumber');
                $list->setParameter('partNumber', $filters["partNumber"]);
            }
            if(isset($filters["name"])){
                $list->andWhere("p.name LIKE '%".$filters["name"]."%'");
            }
            if(isset($filters["withdrawalDateFrom"])){
                $list->andWhere("po.date>=:withdrawalDateFrom");
                $list->setParameter('withdrawalDateFrom', $filters["withdrawalDateFrom"]);
            }
            if(isset($filters["withdrawalDateTo"])){
                $list->andWhere("po.date<=:withdrawalDateTo");
                $list->setParameter('withdrawalDateTo', $filters["withdrawalDateTo"]);
            }
            if(isset($filters['type'])){
                $list->andWhere("t.name =:type");
                $list->setParameter('type', $filters['type']);
            }
        }
    	return $list;
    }
}
