<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
    	$em = $this->getEntityManager();

        $list = $this->createQueryBuilder('p')
            ->select('p.id', 'p.name', 'p.partNumber', 'p.stock', 'p.provider', 'p.stockMinimum', 'p.description', 'p.presentation', 'p.analysisMethod', 't.name AS nameType', 'p.observations')
            ->leftJoin("p.type", "t")
            ->orderBy('p.name', 'ASC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('p')
            ->select('COUNT(p.id) as conta')
            ->leftJoin("p.type", "t");

        $list = self::fillFilersQuery($filters, $list);
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }

    public function productsForJson($filters, $paginate=1)
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('p')
            ->select('p.id', 'p.name AS text', 'p.partNumber', 'p.stock', 'p.provider', 'p.stockMinimum', 'p.description', 'p.presentation', 'p.analysisMethod', 't.name AS nameType', 'p.observations', 't.expirationMonths', 't.destructionMonths')
            ->leftJoin("p.type", "t")
            ->orderBy('p.name', 'ASC');

        if(!empty($filters)){
            if(isset($filters["partNumber"])){
                $list->orWhere("p.partNumber LIKE '%".$filters["partNumber"]."%'");
            }

            if(isset($filters["name"])){
                $list->orWhere("p.name LIKE '%".$filters["name"]."%'");
            }
        }

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    private function fillFilersQuery($filters, $list){

        if(!empty($filters)){
            if(isset($filters["id"])){
                $list->andWhere('p.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["partNumber"])){
                $list->andWhere("p.partNumber LIKE '%".$filters["partNumber"]."%'");
            }

            if(isset($filters["name"])){
                $list->andWhere("p.name LIKE '%".$filters["name"]."%'");
            }

            if(isset($filters["provider"])){
                $list->andWhere("p.provider LIKE '%".$filters["provider"]."%'");
            }

            if(isset($filters["stock_from"])){
                $list->andWhere("p.stock>=:stock_from");
                $list->setParameter('stock_from', $filters["stock_from"]);
            }

            if(isset($filters["stock_to"])){
                $list->andWhere("p.stock<=:stock_to");
                $list->setParameter('stock_to', $filters["stock_to"]);
            }

            if(isset($filters["minimum_stock_from"])){
                $list->andWhere("p.stockMinimum>=:minimum_stock_from");
                $list->setParameter('minimum_stock_from', $filters["minimum_stock_from"]);
            }

            if(isset($filters["minimum_stock_to"])){
                $list->andWhere("p.stockMinimum<=:minimum_stock_to");
                $list->setParameter('minimum_stock_to', $filters["minimum_stock_to"]);
            }

            if(isset($filters["type"])){
                $list->andWhere('p.type=:type');
                $list->setParameter('type', $filters["type"]);
            }
        }

        return $list;
    }
}
