<?php

namespace Nononsense\HomeBundle\Entity;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * ProductsInputsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsInputsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('pi')
            ->select('pi')
            ->innerJoin("pi.product", "p")
            ->innerJoin("p.type", "t")
            ->innerJoin("pi.state", "s")
            ->orderBy('pi.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);

        if ($paginate == 1 && isset($filters["limit_from"])) {
            $list->setFirstResult($filters["limit_from"] * $filters["limit_many"])->setMaxResults(
                $filters["limit_many"]
            );
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = [])
    {
        $list = $this->createQueryBuilder('pi')
            ->select('COUNT(pi.id) as conta')
            ->innerJoin("pi.product", "p")
            ->innerJoin("p.type", "t")
            ->innerJoin("pi.state", "s");

        $list = self::fillFilersQuery($filters, $list);
        $query = $list->getQuery();
        return $query->getSingleResult()["conta"];
    }

    private function fillFilersQuery($filters, $list)
    {
        if (!empty($filters)) {
            if (isset($filters["partNumber"])) {
                $list->andWhere('p.partNumber=:partNumber');
                $list->setParameter('partNumber', $filters["partNumber"]);
            }
            if (isset($filters["name"])) {
                $list->andWhere("p.name LIKE '%" . $filters["name"] . "%'");
            }
            if (isset($filters["provider"])) {
                $list->andWhere("p.provider LIKE '%" . $filters["provider"] . "%'");
            }
            if (isset($filters["receptionDateFrom"])) {
                $list->andWhere("pi.receptionDate>=:receptionDateFrom");
                $list->setParameter('receptionDateFrom', $filters["receptionDateFrom"]);
            }
            if (isset($filters["receptionDateTo"])) {
                $list->andWhere("pi.receptionDate<=:receptionDateTo");
                $list->setParameter('receptionDateTo', $filters["receptionDateTo"]);
            }
            if (isset($filters["expiryDateFrom"])) {
                $list->andWhere("pi.expiryDate>=:expiryDateFrom");
                $list->setParameter('expiryDateFrom', $filters["expiryDateFrom"]);
            }
            if (isset($filters["expiryDateTo"])) {
                $list->andWhere("pi.expiryDate<=:expiryDateTo");
                $list->setParameter('expiryDateTo', $filters["expiryDateTo"]);
            }
            if (isset($filters["destructionDateFrom"])) {
                $list->andWhere("pi.destructionDate>=:destructionDateFrom");
                $list->setParameter('destructionDateFrom', $filters["destructionDateFrom"]);
            }
            if (isset($filters["destructionDateTo"])) {
                $list->andWhere("pi.destructionDate<=:destructionDateTo");
                $list->setParameter('destructionDateTo', $filters["destructionDateTo"]);
            }
            if (isset($filters["openDateFrom"])) {
                $list->andWhere("pi.openDate>=:openDateFrom");
                $list->setParameter('openDateFrom', $filters["openDateFrom"]);
            }
            if (isset($filters["openDateTo"])) {
                $list->andWhere("pi.openDate<=:openDateTo");
                $list->setParameter('openDateTo', $filters["openDateTo"]);
            }
            if(isset($filters['type'])){
                $list->andWhere("t.slug =:type");
                $list->setParameter('type', $filters['type']);
            }
            if (isset($filters['state'])) {
                $list->andWhere("s.id =:state");
                $list->setParameter('state', $filters['state']);
            }
            if (isset($filters['internalCode'])) {
                $list->andWhere("p.internalCode =:internalCode");
                $list->setParameter('internalCode', $filters['internalCode']);
            }
            if (isset($filters['expired']) && $filters['expired'] === true) {
                $now = new Datetime();
                $list->andWhere("pi.destructionDate<=:destructionDateTo");
                $list->setParameter('destructionDateTo', $now->format('Y-m-d H:i:s'));
                $list->orWhere("pi.expiryDate<=:expiryDateTo");
                $list->setParameter('expiryDateTo', $now->format('Y-m-d H:i:s'));
                $list->andWhere("s.id NOT IN (:endState, :expiredState)");
                $list->setParameter('expiredState', $filters['expiredState']);
                $list->setParameter('endState', $filters['endState']);
            }
        }

        return $list;
    }

    public function getOneByQrCode($qrCode)
    {
        $list = $this->createQueryBuilder('pi')
            ->select('pi')
            ->innerJoin("pi.product", "p")
            ->innerJoin("p.type", "t")
            ->andWhere('pi.qrCode = :qrCode')
            ->setParameter('qrCode', $qrCode)
            ->andWhere('pi.remainingAmount > 0')
            ->orderBy('pi.id', 'DESC')
            ->setMaxResults(1);

        $query = $list->getQuery();
        return $query->getOneOrNullResult();
    }

    public function listForStock($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('pi')
            ->select('t.name as productType', 'p.name as productName', 'p.partNumber as partNumber',
                'p.casNumber as casNumber', 'p.internalCode as internalCode', 'p.provider as provider',
                'p.presentation as presentation', 'MAX(pi.destructionDate) as destructionDate', 's.name as state',
                'p.stock as stock', 'p.stockMinimum as minStock', 'MAX(pi.observations) as observations', 'p.active as active',
                'p.id as idProduct', 'pi.qrCode as qrCode')
            ->innerJoin("pi.product", "p")
            ->innerJoin("p.type", "t")
            ->innerJoin("pi.state", "s")
            ->groupBy('pi.qrCode')
            ->addGroupBy('p')
            ->addGroupBy('t')
            ->addGroupBy('s');
//            ->orderBy('destructionDate', 'DESC');

        $list = self::fillFilersQuery($filters, $list);
        if ($paginate == 1 && isset($filters["limit_from"])) {
            $list->setFirstResult($filters["limit_from"] * $filters["limit_many"])->setMaxResults(
                $filters["limit_many"]
            );
        }
        $query = $list->getQuery();

        return $query->getResult();
    }

    public function countForStock($filters = [])
    {
        $list = $this->createQueryBuilder('pi')
            ->select('COUNT(DISTINCT pi.qrCode) as conta')
            ->innerJoin("pi.product", "p")
            ->innerJoin("p.type", "t")
            ->innerJoin("pi.state", "s")
            ->groupBy("pi.qrCode", "s");

        $list = self::fillFilersQuery($filters, $list);
        $query = $list->getQuery();

        return count($query->getResult());
    }
}
