<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('p')
            ->innerJoin("p.type", "t")
            ->orderBy('p.name', 'ASC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        $result = $query->getResult();
        return $result;
    }

    public function count($filters = array())
    {
        $list = $this->createQueryBuilder('p')
            ->select('COUNT(p.id) as conta')
            ->innerJoin("p.type", "t");

        $list = self::fillFilersQuery($filters, $list);
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }

    public function productsForJson($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('p')
            ->select('p.id', 'p.name AS text', 'p.partNumber', 'p.stock', 'p.provider', 'p.stockMinimum', 'p.description', 'p.presentation', 'p.analysisMethod', 't.name AS nameType', 'p.observations', 't.expirationMonths', 't.destructionMonths')
            ->innerJoin("p.type", "t")
            ->orderBy('p.name', 'ASC');

        $list->andWhere("p.active=1");
        $list->andWhere('p.destroyed=0');

        if(!empty($filters)){

            $other_where = '';

            if(isset($filters["partNumber"])){
                $other_where.="p.partNumber LIKE '%".$filters["partNumber"]."%'";
            }

            if(isset($filters["name"])){
                $other_where.=" OR p.name LIKE '%".$filters["name"]."%'";
            }

            $list->andWhere($other_where);
        }

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    private function fillFilersQuery($filters, $list)
    {
        if(!empty($filters)){
            if(isset($filters["partNumber"])){
                $list->andWhere("p.partNumber LIKE '%".$filters["partNumber"]."%'");
            }

            if(isset($filters["casNumber"])){
                $list->andWhere("p.casNumber LIKE '%".$filters["casNumber"]."%'");
            }

            if(isset($filters["name"])){
                $list->andWhere("p.name LIKE '%".$filters["name"]."%'");
            }

            if(isset($filters["active"])){
                if($filters["active"]==2){
                    $filters["active"]=0;
                }else{
                    $filters["active"]=1;
                }
                $list->andWhere("p.active=:active");
                $list->setParameter('active', $filters["active"]);
            }

            if(isset($filters["stock_from"])){
                $list->andWhere("p.stock>=:stock_from");
                $list->setParameter('stock_from', $filters["stock_from"]);
            }

            if(isset($filters["stock_to"])){
                $list->andWhere("p.stock<=:stock_to");
                $list->setParameter('stock_to', $filters["stock_to"]);
            }

            if(isset($filters["type"])){
                $list->andWhere("t.name = :type");
                $list->setParameter('type', $filters["type"]);
            }

            if(isset($filters["underMinimumStock"])){
                if($filters["underMinimumStock"]==1){
                    $list->andWhere("p.stock < p.stockMinimum");
                }
                if($filters["underMinimumStock"]==2){
                    $list->andWhere("p.stock >= p.stockMinimum");
                }
            }
        }

        return $list;
    }
}
