<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsOutputsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsOutputsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
    	$em = $this->getEntityManager();

        $list = $this->createQueryBuilder('po')
            ->select('po.id', 'po.amount', 'p.name AS productName', 'po.date', 'p.partNumber as productPartNumber', 'pi.id AS productInputId')
            ->leftJoin("po.productInput", "pi")
            ->leftJoin("pi.product", "p")
            ->orderBy('po.date', 'ASC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('po')
            ->select('COUNT(po.id) as conta')
            ->leftJoin("po.productInput", "pi")
            ->leftJoin("pi.product", "p");

        $list = self::fillFilersQuery($filters, $list);
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }

    private function fillFilersQuery($filters, $list){

    	if(!empty($filters)){

        	if(isset($filters["partNumber"])){
                $list->andWhere('p.partNumber=:partNumber');
                $list->setParameter('partNumber', $filters["partNumber"]);
            }

            if(isset($filters["name"])){
                $list->andWhere("p.name LIKE '%".$filters["name"]."%'");
            }

            if(isset($filters["withdrawalDateFrom"])){
                $list->andWhere("po.date>=:withdrawalDateFrom");
                $list->setParameter('withdrawalDateFrom', $filters["withdrawalDateFrom"]);
            }
            if(isset($filters["withdrawalDateTo"])){
                $list->andWhere("po.date<=:withdrawalDateTo");
                $list->setParameter('withdrawalDateTo', $filters["withdrawalDateTo"]);
            }

        }

    	return $list;
    }
}
