<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QrsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QrsRepository extends EntityRepository
{
	public function list($filters, $paginate=1)
    {
    	$em = $this->getEntityManager();

        $list = $this->createQueryBuilder('qr')
            ->select('qr.id', 'qr.name', 't.name typeqr')
            ->leftJoin("qr.type", "t")
            ->orderBy('qr.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);

        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters = array())
    {
        $em = $this->getEntityManager();

        $list = $this->createQueryBuilder('qr')
            ->select('COUNT(qr.id) as conta');

        $list = self::fillFilersQuery($filters, $list);
        
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }


    private function fillFilersQuery($filters, $list){

        if(!empty($filters)){
            if(isset($filters["id"])){
                $list->andWhere('p.id=:id');
                $list->setParameter('id', $filters["id"]);
            }

            if(isset($filters["name"])){
                $list->andWhere("p.name LIKE '%".$filters["name"]."%'");
            }
        }

        return $list;
    }
}
