<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RCStatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RCStatesRepository extends EntityRepository
{
    public function getRetentionCumplimentationStates()
    {
        $ARCHIVADA = 3; $CANCELADA = 4;
        $rcStatesForCumplimentations = [$ARCHIVADA, $CANCELADA];
        $em = $this->getEntityManager();
        $list = $this->createQueryBuilder('rcs')
            ->select('rcs.id, rcs.name')
            ->where("rcs.id in (" . implode(",", $rcStatesForCumplimentations) . ")");
        return $list->getQuery()->getResult();
    }
}
