<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevisionRepository extends EntityRepository
{

    /**
     * List of Master_Workflows with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listRevisions($page = 1, $max = 10, $sort = 'id')
    {
        return null;
    }
}
