<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RevisionInstanciaWorkflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevisionInstanciaWorkflowRepository extends EntityRepository
{

    public function listValidacionesPendientes($user_logged,$arrayTypes)
    {

        $list = $this->createQueryBuilder('n')
            ->select('n.id','ms.name','ms.description','c.name as companyName','iw.id as registroid','mt.fechainicio as fecha','mt.lote','mt.material as codigo','n.type','u.name as namecreated')
            ->leftJoin("n.instanciaWorkflowEntity", "iw")
            ->leftJoin("iw.Master_Workflow_Entity", "ms")
            ->leftJoin("ms.category", "c")
            ->leftJoin("iw.userCreatedEntiy", "u")
            ->innerJoin("iw.metaData", "mt")
            ->andWhere('n.status = 0')
            ->andWhere('iw.usercreatedid != :user')
            ->andWhere('n.type in (:typearray)')
            ->setParameter('user',$user_logged)
            ->orderBy('n.id', 'DESC');

        $list->setParameter('typearray', $arrayTypes);

        $query = $list->getQuery();

        return $query->getResult();
    }



}
