<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TMCumplimentationsTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TMCumplimentationsTypeRepository extends EntityRepository
{
	public function search($type,$filters)
    {
        $em = $this->getEntityManager();

        switch($type){
            case "list":
                $list = $this->createQueryBuilder('t')
                    ->select('t');

                break;
            case "count":
                $list = $this->createQueryBuilder('t')
                    ->select('COUNT(t.id) as conta');
                break;
        }
            
        if($type=="list"){
            $list->orderBy('t.id', 'ASC');
        }

        if(isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }

        $query = $list->getQuery();


        switch($type){
            case "list":
                return $query->getResult();
                break;
            case "count":
                return $query->getSingleResult()["conta"];
                break;
        }
    }
}
