<?php

namespace Nononsense\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AreasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TMTemplatesRepository extends EntityRepository
{
	public function listActiveForRequest($filters)
    {
        $em = $this->getEntityManager();

        $sintax=" WHERE t.tmState=6 AND t.id NOT IN (SELECT aux.template_id FROM Nononsense\HomeBundle\Entity\TMTemplates aux WHERE aux.tmState IN (1,2,3,4,5))";
        $logical=" AND ";

        if(!empty($filters)){

            if(isset($filters["name"])){
	            $terms = explode(" ", $filters["name"]);
	            foreach($terms as $key => $term){
	                $sintax.=$logical." (t.name LIKE :name".$key. " OR a.name LIKE :nameArea".$key.")";
	                $parameters["name".$key]="%".$term."%";
	                $parameters["nameArea".$key]="%".$term."%";
	                $logical=" AND ";
	            }
	        }
        }


        $query = $em->createQuery("SELECT t FROM Nononsense\HomeBundle\Entity\TMTemplates t LEFT JOIN Nononsense\HomeBundle\Entity\Areas a WITH t.area=a.id ".$sintax." ORDER BY t.name DESC");

        if(isset($filters["limit_from"])){
            $query->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }
        
        if(!empty($parameters)){
            $query->setParameters($parameters);
        }

        $items=$query->getResult();

        return $items;
    }
}
