<?php

namespace Nononsense\NotificationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessagesUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesUsersRepository extends EntityRepository
{
    /**
     * Gets the count of read messages
     *
     * @return int
     */
    public function findReadMessages($userid)
    {
        $read = $this->createQueryBuilder('mu')
                       ->select('count(mu.id)')
                       ->where('mu.user = :id' )
                       ->setParameter('id', $userid);

        $query = $read->getQuery();
 
        return $query->getSingleScalarResult();
    }
}
