<?php

namespace Nononsense\NotificationsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsModelsRepository extends EntityRepository
{
    /**
     * Gets the list of notificationsModels
     *
     * @return Paginator
     */
    public function list($page=1, $max=20): Paginator
    {
        $notificationsModels = $this->createQueryBuilder('nm')
            ->select('nm', 't', 'u', 'g', 's')
            ->join('nm.templateId', 't') //join notificationsModels with TMTemplates
            ->join('nm.user', 'u') //join notificationsModels with the users
            ->join('nm.group', 'g') //join notificationsModels with the groups
            ->join('nm.state', 's') //join notificationsModels with the states
            ->addOrderBy('nm.created','DESC');
        ;
        $notificationsModels->setFirstResult(($page-1) * $max);
        $notificationsModels->setMaxResults($max);

        return new Paginator($notificationsModels);
    }

}
