<?php

namespace Nononsense\NotificationsBundle\Entity;
use Doctrine\ORM\Tools\Pagination\Paginator;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsRepository extends EntityRepository
{
    /**
     * Gets the list of messages associated with a user
     *
     * @return Paginator
     */
    public function findUserMessages($userid, $page=1, $max=20, $query = 'q', $group = 0)
    {
        $messag = $this->createQueryBuilder('n')
                       ->select('n', 'g', 'mu', 'u', 'n.id as HIDDEN notificationId')
                       ->join('n.groups', 'g')//join notifications with groups
                       ->join('g.users', 'gu')//join groups with the users
                       ->join('n.user', 'u')//join with the users table
                       ->leftJoin('n.messages', 'mu', 'WITH', 'mu.user = :id')//join with the table of messages read/deleted by that user
                       ->where('gu.user = :id AND n.user <> :id AND (mu.trash = 0 OR mu.trash is NULL)')//select the user
                       ->setParameter('id', $userid);
        if ($group) {
            $messag->andWhere('g.id = :gid')
                 ->setParameter('gid', $group);
        }
        if (!empty($query) && $query != 'q') {
            $messag->andWhere('n.subject LIKE :query OR u.name LIKE :query')
                 ->setParameter('query', '%' . $query . '%');
        }
                
        $messag->orderBy('notificationId', 'DESC');
        
        $messag->setFirstResult(($page-1) * $max);
        $messag->setMaxResults($max);
 
        return new Paginator($messag);
        
    }
    
    /**
     * Gets the list of messages associated with a user
     *
     * @return Paginator
     */
    public function findOwnMessages($userid, $page=1, $max=20, $query = 'q', $group = 0)
    {
        $messag = $this->createQueryBuilder('n')
                      ->select('n','n.id as HIDDEN notificationId')
                       ->join('n.user', 'u')//join with the users table
                       ->where('n.user = :id' )
                       ->setParameter('id', $userid);
        if (!empty($query) && $query != 'q') {
            $messag->andWhere('n.subject LIKE :query OR u.name LIKE :query')
                 ->setParameter('query', '%' . $query . '%');
        }     
        $messag->orderBy('notificationId', 'DESC');
        
        $messag->setFirstResult(($page-1) * $max);
        $messag->setMaxResults($max);
 
        return new Paginator($messag);
    }
    
    /**
     * Gets the list of messages sent to the trash
     *
     * @return Paginator
     */
    public function findTrashMessages($userid, $page=1, $max=20, $query = 'q', $group = 0)
    {
        $messag = $this->createQueryBuilder('n')
                       ->select('n', 'g', 'mu','n.id as HIDDEN notificationId')
                       ->join('n.groups', 'g')
                       ->join('g.users', 'gu')
                       ->join('n.user', 'u')//join with the users table
                       ->join('n.messages', 'mu', 'WITH', 'mu.user = :id')
                       ->where('gu.user = :id AND n.user <> :id AND mu.trash = 1' )
                       ->setParameter('id', $userid);
        if (!empty($query) && $query != 'q') {
            $messag->andWhere('n.subject LIKE :qu OR u.name LIKE :qu')
                   ->setParameter('qu', '%' . $query . '%');
        }
                
        $messag->orderBy('notificationId', 'DESC');
        
        $messag->setFirstResult(($page-1) * $max);
        $messag->setMaxResults($max);
 
        return new Paginator($messag);
    }
    
    /**
     * Cheks if the user has permission to view a message
     *
     * @return boolean
     */
    public function check($userid, $messageId)
    {
        $messag = $this->createQueryBuilder('n')
                       ->select('n.id')
                       ->join('n.groups', 'g')//join notifications with groups
                       ->join('g.users', 'gu')//join groups with the users
                       ->where('gu.user = :id' )//select the user
                       ->andWhere('n.id = :messageId')
                       ->setParameter('id', $userid)
                       ->setParameter('messageId', $messageId);
        $query = $messag->getQuery();
        
        if ($query->getResult()) {
            return true;
        } else {
            return false;
        }
        
    }
    
    /**
     * Gets the list of messages associated with a user
     *
     * @return Paginator
     */
    public function findUnreadMessages($userid)
    {
        $read = $this->createQueryBuilder('n')
                     ->select('n.id')
                     ->join('n.groups', 'g')//join notifications with groups
                     ->join('g.users', 'gu')//join groups with the users
                     ->join('n.messages', 'mu', 'WITH', 'mu.user = :userid')//join with the table of messages read/deleted by that user
                     ->where('gu.user = :id AND n.user <> :id')//select the user
                     ->setParameter('userid', $userid)
                     ->setParameter('id', $userid)
                     ->groupBy('n.id');       
        
        $query = $read->getQuery();    
        $result = $query->getResult();
        $r = count($result);
        $total = $this->createQueryBuilder('n')
                     ->select('n.id')
                     ->join('n.groups', 'g')//join notifications with groups
                     ->join('g.users', 'gu')//join groups with the users
                     ->where('gu.user = :id AND n.user <> :id')//select the user
                     ->setParameter('id', $userid)
                     ->groupBy('n.id');
        
        $query = $total->getQuery();    
        $total = $query->getResult();
        $t = count($total);
                
        return $t - $r;
        
    }
    
    /**
     * Gets the last 3 messages associated with the user
     *
     * @return Paginator
     */
    public function findWidgetMessages($userid)
    {
        $messag = $this->createQueryBuilder('n')
                       ->select('n.id, n.subject, n.created, (u.id) AS authorid')
                       ->join('n.groups', 'g')//join notifications with groups
                       ->join('g.users', 'gu')//join groups with the users
                       ->join('n.user', 'u')//join with the users table
                       ->leftJoin('n.messages', 'mu', 'WITH', 'mu.user = :id')//join with the table of messages read/deleted by that user
                       ->where('gu.user = :id AND n.user <> :id AND (mu.trash = 0 OR mu.trash is NULL)')//select the user
                       ->setParameter('id', $userid);
       
        $messag->setMaxResults(3);     
        $messag->orderBy('n.id', 'DESC');
        
        $query = $messag->getQuery();
 
        return $query->getResult();
        
    }

    public function listBy($filters, $limit = 20){

        $list  = $this->createQueryBuilder('n')
                        ->join("n.user", "u", "WITH", 'u = :user')
                        ->setParameter('user', $filters['user'])
                        ->addOrderBy('n.created','ASC');

        $list->setFirstResult($limit*($filters["page"]-1))->setMaxResults($limit);

        $paginator = new Paginator($list);
        $paginator->getQuery()->setFirstResult($limit*($filters['page']-1))->setMaxResults($limit);
        $paginator->setUseOutputWalkers(false);

        return $paginator;
    }

    public function countBy($filters){

        $list  = $this->createQueryBuilder('n')
                  ->select('COUNT(n.id)')
                  ->join("n.user", "u", "WITH", 'u = :user')
                  ->setParameter('user', $filters['user']);

        if (isset($filters['unread']) && $filters['unread']) {
           $list->andWhere('n.created = n.modified');
        }

        $query = $list->getQuery()->getSingleScalarResult();

        return $query;
    }
}
