<?php

namespace Nononsense\NotificationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationsModelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsModelsRepository extends EntityRepository
{
   const TEMPLATE_ID = "templateId";

    public function list($filters, $paginate=1)
    {
        $list = $this->createQueryBuilder('n')
            ->select('n')
            ->orderBy('n.id', 'DESC');

        $list = self::fillFilersQuery($filters, $list);
        if($paginate==1 && isset($filters["limit_from"])){
            $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
        }
        $query = $list->getQuery();

        return $query->getResult();
    }

    public function count($filters)
    {
        $list = $this->createQueryBuilder('n')
            ->select('COUNT(n.id) as conta')
        ;

        $list = self::fillFilersQuery($filters, $list);
        $query = $list->getQuery();

        return $query->getSingleResult()["conta"];
    }

    private function fillFilersQuery($filters, $list){

        if(isset($filters[self::TEMPLATE_ID])){
            $terms = explode(" ", $filters[self::TEMPLATE_ID]);
            foreach($terms as $key => $term){
                $list->andWhere('n.templateId  = :id');
                $list->setParameter('id', $term);
            }
        }

        return $list;
    }
}
