<?php

namespace Nononsense\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    /**
     * List of news with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listNews($page=1, $max=10, $sort= 'id', $query= 'q', $admin = false)
    {
        $list = $this->createQueryBuilder('n')
                     ->select('n.id, n.title, n.body, n.created, n.isActive');
        if (!$admin) {
            $list->where('n.isActive = :is_active')
                 ->setParameter('is_active', true);
        }
        if (!empty($query) && $query != 'q') {
            $list->andWhere('n.title LIKE :query OR n.body LIKE :query')
                 ->setParameter('query', '%' . $query . '%');
        }
        
        $list->orderBy('n.' . $sort, 'DESC');
 
        $list->setFirstResult(($page-1) * $max);
        $list->setMaxResults($max);
 
        $paginator = new Paginator($list);
        //this is a hack to be able to choose some certain fields
        $paginator->setUseOutputWalkers(false);
        
        return $paginator;
    }
    
    /**
     * Counts the total number of news
     *
     * @return int
     */
    public function countTotal()
    {
        $qb = $this->createQueryBuilder('n');
        $qb->select('COUNT(n)');

        $count = $qb->getQuery()->getSingleScalarResult();
 
        return $count;
    }
    
    /**
     * Gets a single news item together with the user that created it
     *
     * @return array
     */
    public function findOneByIdJoinedToUser($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT n, u FROM NononsenseNewsBundle:News n
                JOIN n.user u
                WHERE n.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
