<?php

namespace Nononsense\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AccountRequestsGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRequestsGroupsRepository extends EntityRepository
{
	public function listBy($filter, $limit = 20){
        $list  = $this->createQueryBuilder('arg')
                ->select('arg', 'r', 'grp')
        		->join('arg.requestId', 'r')
                ->join('arg.groupId', 'grp')
                ->addOrderBy('r.created', 'ASC');

        if (isset($filter['status']) && is_numeric($filter['status'])) {
            $list->andWhere('arg.status = :status');
            $list->setParameter('status', $filter["status"]);
        }

        if (isset($filter['username']) && $filter['username']) {
            $list->andWhere('r.username LIKE :username');
            $list->setParameter('username', '%'.$filter["username"].'%');
        }

        if(isset($filter["from"]) && $filter['from']){
            $list->andWhere('r.created >= :from');
            $list->setParameter('from', $filter["from"]);
        }

        if(isset($filter["until"]) && $filter['until']){
            $list->andWhere('r.created <= :until');
            $list->setParameter('until', $filter["until"]." 23:59:00");
        }

        if(isset($filter["mudid"]) && $filter['mudid']){
            $list->andWhere('r.mudId = :mudid');
            $list->setParameter('mudid', $filter["mudid"]);
        }

        $list->setFirstResult($limit*($filter["page"]-1))->setMaxResults($limit);

        $accountRequests['rows']  = $list->getQuery()->getResult();
        $accountRequests['count'] = count(new Paginator($list));

        return $accountRequests;
    }
}
