<?php

namespace Nononsense\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AccountRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRequestsRepository extends EntityRepository
{
	 public function listBy($filter, $limit = 20){
        $list  = $this->createQueryBuilder('u')
                ->addOrderBy('u.status','ASC')
                ->addOrderBy('u.created','ASC');

        if (isset($filter['status']) && is_numeric($filter['status'])) {
            $list->andWhere('u.status = :status');
            $list->setParameter('status', $filter["status"]);
        }

        if (isset($filter['username']) && $filter['username']) {
            $list->andWhere('u.username LIKE :username');
            $list->setParameter('username', '%'.$filter["username"].'%');
        }

        if(isset($filter["from"]) && $filter['from']){
            $list->andWhere('u.created >= :from');
            $list->setParameter('from', $filter["from"]);
        }

        if(isset($filter["until"]) && $filter['until']){
            $list->andWhere('u.created <= :until');
            $list->setParameter('until', $filter["until"]." 23:59:00");
        }

        $list->setFirstResult($limit*($filter["page"]-1))->setMaxResults($limit);

        $accountRequests['rows']  = $list->getQuery()->getResult();
        $accountRequests['count'] = count(new Paginator($list));

        return $accountRequests;
    }

}
