<?php

namespace Nononsense\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsSubseccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsSubseccionesRepository extends EntityRepository
{
}
