<?php

namespace Nononsense\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SectionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionsRepository extends EntityRepository
{
}
