<?php

namespace Nononsense\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubseccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubseccionesRepository extends EntityRepository
{
}
