<?php

namespace Nononsense\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    /**
     * List of users with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listUsers($page = 1, $max = 10, $sort = 'orderId', $query = 'q', $admin = false)
    {
        $list = $this->createQueryBuilder('u');
        $list->addSelect('u', 'u.id as HIDDEN orderId');
        if (!$admin) {
            $list->where('u.isActive = :is_active')
                ->setParameter('is_active', true);
        }
        if (!empty($query) && $query != 'q') {
            $list->andWhere('u.username LIKE :query OR u.name LIKE :query')
                ->setParameter('query', '%' . $query . '%');
        }

        $list->orderBy($sort, 'DESC');

        $list->setFirstResult(($page - 1) * $max);
        $list->setMaxResults($max);

        return new Paginator($list);
    }

    public function listUsersLikeName($usuario){
        $list = $this->createQueryBuilder('u')
            ->andWhere('u.name LIKE :query')
            ->setParameter('query', '%' . $usuario . '%');

        $query = $list->getQuery();

        return $query->getResult();
    }

    /**
     * Gest user names and ids
     *
     * @return Paginator
     */
    public function getUserNames()
    {
        $list = $this->createQueryBuilder('u')
            ->select('u.id, u.name')
            ->orderBy('u.name', 'ASC');

        return $list->getQuery()->getResult();
    }

    /**
     * Get just user names and ids
     *
     * @param int $groupId
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function findAllUsersNotInGroup($groupId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM NononsenseUserBundle:Users u 
                 JOIN u.roles r
                 WHERE  r.id > :filter AND u.isActive = true AND u.id NOT IN
                (SELECT  IDENTITY(g.user) FROM NononsenseGroupBundle:GroupUsers g WHERE g.group = :id)'
            )->setParameter('filter', 0)
            ->setParameter('id', $groupId);
        //comment: the IDENTITY operator was need because it was a composite field
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    /**
     * Get just user names and ids
     *
     * @param int $groupId
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function findAllUsersNotInMicrosite($micrositeId, $type)
    {
        $q = 'SELECT u FROM NononsenseUserBundle:Users u 
                 JOIN u.roles r
                 WHERE  ';
        if ($type == 'member') {
            $q .= 'r.id < 3 ';
        } else {
            $q .= 'r.id > 1';
        }
        $q .= 'AND u.isActive = true AND u.id NOT IN
                (SELECT  IDENTITY(m.user) FROM NononsenseMicrositeBundle:MicrositeUsers m WHERE m.microsite = :id)';
        $query = $this->getEntityManager()
            ->createQuery($q)
            ->setParameter('id', $micrositeId);
        //comment: the IDENTITY operator was need because it was a composite field
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    /**
     * Get user names and emails with a minimum role permission
     *
     * @param int $role
     * @return Array
     */
    public function listUsersByRole($role)
    {
        $users = $this->createQueryBuilder('u')
            ->select('u.name', 'u.email')
            ->join('u.roles', 'r')
            ->where('r.id > :role')
            ->andWhere('u.isActive = true')
            ->setParameter('role', $role)
            ->orderBy('u.name', 'ASC');

        return $users->getQuery()->getArrayResult();

    }

    /**
     * Gest list of users with basic info and roles
     *
     * @return Array
     */
    public function fullUserList()
    {

        $users = $this->createQueryBuilder('u')
            ->select('u.id', 'u.name', 'u.position', 'u.email', 'u.phone', 'u.created', 'r.name as rol')
            ->join('u.roles', 'r')
            ->orderBy('u.name', 'ASC');

        return $users->getQuery()->getArrayResult();
    }

    /**
     * Get user names and emails with a minimum role permission
     *
     * @param array $sections
     * @return Array
     */
    public function listSignerUsersBySection($sections, $departamento)
    {
        //var_dump($departamento);
        if ($departamento == null || $departamento == 1) {
            $users = $this->createQueryBuilder('u')
                ->select('u.name', 'u.email')
                ->innerJoin('u.groups', 'gs')
                ->innerJoin('gs.group', 'g')
                ->orWhere('g.codigo = :group7 ')
                ->orWhere('g.codigo = :group14')
                ->orWhere('g.codigo = :group3')
                ->orWhere('g.codigo = :group13')
                //->orWhere('g.codigo = :group15')
                ->setParameter('group7', 'UPDS0007')
                ->setParameter('group14', 'UPDS0014')
                ->setParameter('group3', 'UPDS0003')
                ->setParameter('group13', 'UPDS0013')
                //->setParameter('group15', 'UPDS0015')
                ->orderBy('u.name', 'ASC');

        } elseif ($departamento == 2) {

            $users = $this->createQueryBuilder('u')
                ->select('u.name', 'u.email')
                ->innerJoin('u.groups', 'gs')
                ->innerJoin('gs.group', 'g')
                ->orWhere('g.codigo = :group9 ')
                //->orWhere('g.codigo = :group14')
                //->orWhere('g.codigo = :group3')
                //->orWhere('g.codigo = :group13')
                ->orWhere('g.codigo = :group15')
                ->setParameter('group9', 'UPDS0009')
                //->setParameter('group14', 'UPDS0014')
                //->setParameter('group3', 'UPDS0003')
                //->setParameter('group13', 'UPDS0013')
                ->setParameter('group15', 'UPDS0015')
                ->orderBy('u.name', 'ASC');
        }


        if (count($sections) > 0) {
            $users->andWhere('s.id IN (:sects)');
            $users->setParameter('sects', $sections);
            $users->innerJoin('u.sections', 'ss');
            $users->innerJoin('ss.section', 's');
        }


        return $users->getQuery()->getArrayResult();

    }

    /**
     * Get user names and emails with a minimum role permission
     *
     * @return Array
     */
    public function listSignerUsers($section, $departamento)
    {

        if ($departamento == null || $departamento == 1) {
            $users = $this->createQueryBuilder('u')
                ->select('u.name', 'u.email', 'u.id')
                ->innerJoin('u.groups', 'gs')
                ->innerJoin('gs.group', 'g')
                ->orWhere('g.codigo = :group7 ')
                ->orWhere('g.codigo = :group14')
                ->orWhere('g.codigo = :group3')
                ->orWhere('g.codigo = :group13')
                //->orWhere('g.codigo = :group15')
                ->setParameter('group7', 'UPDS0007')
                ->setParameter('group14', 'UPDS0014')
                ->setParameter('group3', 'UPDS0003')
                ->setParameter('group13', 'UPDS0013')
                //->setParameter('group15', 'UPDS0015')
                ->orderBy('u.name', 'ASC');

        } elseif ($departamento == 2) {

            $users = $this->createQueryBuilder('u')
                ->select('u.name', 'u.email', 'u.id')
                ->innerJoin('u.groups', 'gs')
                ->innerJoin('gs.group', 'g')
                ->orWhere('g.codigo = :group9 ')
                ->orWhere('g.codigo = :group15')
                ->setParameter('group9', 'UPDS0009')
                ->setParameter('group15', 'UPDS0015')
                ->orderBy('u.name', 'ASC');
        }

        return $users->getQuery()->getArrayResult();
    }

    /*
     * Get users creation permission
     *  1 -> NO CODIGO (GENERAL)
     *  5 -> LOGISTICA (UPDS0004)
     *  6 -> CTS (UPDS0014)
     *  9 -> J.P. (UPDS0003)
     *  10-> CRT (UPDS0013)
     *  11-> Pool (UPDS0001)
     *  13-> SUPECO (UPDS0015)
     */
    public function listCreationUsers()
    {
        $users = $this->createQueryBuilder('u')
            ->innerJoin('u.groups', 'gs')
            ->innerJoin('gs.group', 'g')
            ->orWhere('g.codigo = :group1 ')
            ->orWhere('g.codigo = :group5')
            ->orWhere('g.codigo = :group6')
            ->orWhere('g.codigo = :group9')
            ->orWhere('g.codigo = :group10')
            ->orWhere('g.codigo = :group11')
            ->orWhere('g.codigo = :group13')
            ->setParameter('group1', 'GENERAL')
            ->setParameter('group5', 'UPDS0004')
            ->setParameter('group6', 'UPDS0014')
            ->setParameter('group9', 'UPDS0003')
            ->setParameter('group10', 'UPDS0013')
            ->setParameter('group11', 'UPDS0001')
            ->setParameter('group13', 'UPDS0015')
            ->orderBy('u.name', 'ASC');

        $query = $users->getQuery();

        return $query->getResult();
    }

    public function listUsersByAreaAndPermission($area,$permission)
    {
        $users = $this->createQueryBuilder('u')
            ->select('u.name', 'u.email', 'u.id')
            ->join('u.groups', 'gu')
            ->join('gu.group', 'g')
            ->join('g.areas', 'a')
            ->join('g.groupsSubsecciones', 'gs')
            ->join('gs.subseccion', 's')
            ->where('a.area = :area')
            ->andWhere('s.nameId = :permission')
            ->andWhere('u.isActive = true')
            ->setParameter('area', $area)
            ->setParameter('permission', $permission)
            ->groupBy('u.id')->addGroupBy('u.name')->addGroupBy('u.email')
            ->orderBy('u.name', 'ASC');

        return $users->getQuery()->getArrayResult();

    }
}
