<?php

namespace Nononsense\GroupBundle\Entity;
use Doctrine\ORM\Tools\Pagination\Paginator;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupUsersRepository extends EntityRepository
{
    /**
     * Gets the list of users associated with a group
     *
     * @return array
     */
    public function findUsersByGroup($page, $max, $id, $query, $type = '')
    {
        $users = $this->createQueryBuilder('g')
                      ->join('g.user', 'u')
                      ->where('g.group = :id')
                      ->setParameter('id', $id);
        
        if ($type == 'admin' || $type == 'member') {
            $users->andWhere('g.type = :type')
                  ->setParameter('type', $type);
        }
        
        if (!empty($query) && $query != 'q') {
            $list->andWhere('u.username LIKE :query OR u.name LIKE :query')
                 ->setParameter('query', '%' . $query . '%');
        }
                
        $users->orderBy('u.name', 'ASC')
              ->setFirstResult(($page-1) * $max)
              ->setMaxResults($max);
 
        return new Paginator($users);
    }
    
    
}
