<?php

namespace Nononsense\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{
    /**
     * List of groups with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listGroups($page=1, $max=10, $sort= 'id', $query= 'q', $admin = false)
    {
        $list = $this->createQueryBuilder('g');
        $list->select('g','g.'.$sort.' as HIDDEN orderby');
        if (!$admin) {
            $list->where('g.isActive = :is_active')
                 ->setParameter('is_active', true);
        }
        if (!empty($query) && $query != 'q') {
            $list->andWhere('g.name LIKE :query OR g.description LIKE :query')
                 ->setParameter('query', '%' . $query . '%');
        }
        
        $list->orderBy('orderby', 'DESC');
 
        $list->setFirstResult(($page-1) * $max);
        $list->setMaxResults($max);
 
        return new Paginator($list);
    }
    
    /**
     * Gets the list of groups associated with a user
     *
     * @return array
     */
    public function findGroupsByUser($userid)
    {
        $groups = $this->createQueryBuilder('g')
                       ->join('g.users', 'gu')
                       ->where('gu.user = :id')
                       ->setParameter('id', $userid);
                
        $groups->orderBy('g.name', 'ASC');
        
        $query = $groups->getQuery();
        
        return $query->getResult();
    }
    
    /**
     * Get the template permissions for different groups
     *
     * @return array
     */
    public function accessList($templateId)
    {
        $access = $this->createQueryBuilder('g')
                       ->select('g', 'a')
                       ->where('g.isActive = 1')
                       ->leftJoin('g.permissions', 'a', 'WITH', 'a.template = :templateId')
                       ->setParameter('templateId', $templateId);
        $query = $access->getQuery();
        
        return $query->getResult();
        
    }
    
    /**
     * Gets the list of users associated with a template via a group
     *
     * @return array
     */
    public function findTemplateAccessGroupsByUser($id, $templateId)
    {
        $groups = $this->createQueryBuilder('g')
                       ->join('g.permissions', 'tag')
                       ->join('g.users', 'u')
                       ->where('g.isActive = 1')
                       ->andWhere('tag.template = :templateId')
                       ->andWhere('tag.read = 1')
                       ->andWhere('u.user = :id')
                       ->setParameter('templateId', $templateId)
                       ->setParameter('id', $id)
                       ->getQuery();

        return $groups->getResult();
    }

    public function findAllGroupsNotInArea($areaId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT g FROM NononsenseGroupBundle:Groups g 
                 WHERE  g.isActive = true AND g.id NOT IN
                (SELECT  IDENTITY(ag.agroup) FROM NononsenseHomeBundle:AreasGroups ag WHERE ag.area = :id)'
            )->setParameter('id', $areaId);
        //comment: the IDENTITY operator was need because it was a composite field
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function listGroupsByAreaAndPermission($area,$permission)
    {
        $groups = $this->createQueryBuilder('g')
            ->select('g.name', 'g.id')
            ->join('g.areas', 'a')
            ->join('g.groupsSubsecciones', 'gs')
            ->join('gs.subseccion', 's')
            ->where('a.area = :area')
            ->andWhere('s.nameId = :permission')
            ->andWhere('g.isActive = true')
            ->setParameter('area', $area)
            ->setParameter('permission', $permission)
            ->orderBy('g.name', 'ASC');

        return $groups->getQuery()->getArrayResult();

    }

    public function listGroupsByPermission($permission)
    {
        $groups = $this->createQueryBuilder('g')
            ->select('g.name', 'g.id')
            ->join('g.groupsSubsecciones', 'gs')
            ->join('gs.subseccion', 's')
            ->andWhere('s.nameId = :permission')
            ->andWhere('g.isActive = true')
            ->setParameter('permission', $permission)
            ->orderBy('g.name', 'ASC');

        return $groups->getQuery()->getArrayResult();

    }

    /**
     * List of groups for selects
     *
     * @return array
     */
    public function listGroupsForSelect()
    {
        $list = $this->createQueryBuilder('g');
        $list->select('g.id, g.name')
            ->where('g.isActive = :is_active')
            ->setParameter('is_active', true);

        $query = $list->getQuery();

        return $query->getResult();
    }

    public function list($type,$filters)
    {
        $em = new ResultSetMapping();

        switch($type){
            case "list":
                $list = $this->createQueryBuilder('g')->select('g.id','g.name','g.isActive','g.color','g.created','g.description');
                if(isset($filters["limit_from"])){
                    $list->setFirstResult($filters["limit_from"]*$filters["limit_many"])->setMaxResults($filters["limit_many"]);
                }
                break;
            case "count":
                $list = $this->createQueryBuilder('g')->select('COUNT(g.id) as conta');
                break;
        }

        if(!empty($filters)){

            if(isset($filters["name"])){
                $terms = explode(" ", $filters["name"]);
                foreach($terms as $key => $term){
                    $list->andWhere('g.name LIKE :name'.$key);
                    $list->setParameter('name'.$key, '%' . $term. '%');
                }
            }
            if(isset($filters["user"])){
                $subquery = $this->createQueryBuilder('sub')
                    ->select('gaux.id')
                    ->from('Nononsense\GroupBundle\Entity\GroupUsers', 'gu')
                    ->leftJoin("gu.user", "uaux")
                    ->leftJoin("gu.group", "gaux");

                $terms = explode(" ", $filters["user"]);
                foreach($terms as $key => $term){
                    $subquery->andWhere('uaux.name LIKE :user'.$key);
                    $subquery->setParameter('user'.$key, '%' . $term. '%');
                }

                $dql = $subquery->getDQL();
                $params = $subquery->getQuery()->getParameters();

                $list->andWhere($list->expr()->in('g.id', $dql));

                foreach ($params as $parameter) {
                    $list->setParameter($parameter->getName(), $parameter->getValue());
                }
            }

            if(isset($filters["state"])){
                switch($filters["state"]){
                    case "active": 
                        $list->andWhere('g.isActive=TRUE');
                        break;
                    case "inactive": 
                        $list->andWhere('g.isActive=FALSE');
                        break;
                }
            }
        }


        

        $query = $list->getQuery();


        switch($type){
            case "list":
                return $query->getResult();
                break;
            case "count":
                return $query->getSingleResult()["conta"];
                break;
        }
    }
}
