<?php

namespace Nononsense\GroupBundle\Entity;
use Doctrine\ORM\Tools\Pagination\Paginator;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupUsersRepository extends EntityRepository
{
    /**
     * Gets the list of users associated with a group
     *
     * @return array
     */
    public function findUsersByGroup($page, $max, $id, $query, $type = '')
    {
        $users = $this->createQueryBuilder('g')
                      ->select('g','u.name as HIDDEN nameUser')
                      ->join('g.user', 'u')
                      ->where('g.group = :id')
                      ->setParameter('id', $id);
        
        if ($type == 'admin' || $type == 'member') {
            $users->andWhere('g.type = :type')
                  ->setParameter('type', $type);
        }
        
        if (!empty($query) && $query != 'q') {
            $list->andWhere('u.username LIKE :query OR u.name LIKE :query')
                 ->setParameter('query', '%' . $query . '%');
        }
                
        $users->orderBy('nameUser', 'ASC')
              ->setFirstResult(($page-1) * $max)
              ->setMaxResults($max);
 
        return new Paginator($users);
    }

    public function isMemberOfAnyGroup($user_id, $groups=[]){
      
      $is_member = 0;

      if(count($groups)>0){

        $ids_groups = implode(",", $groups);

        $users = $this->createQueryBuilder('g')
                      ->where("g.user = :user_id AND g.group IN ($ids_groups)")
                      ->setParameter('user_id', $user_id);


        $query = $users->getQuery();
        $users_groups = $query->getResult();
        if(count($users_groups)>0){
          $is_member = 1;          
        }
      }

      return $is_member;
    }
    
}
