<?php

namespace Nononsense\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{
    /**
     * List of groups with pagination
     *
     * @param int $page
     * @param int $max
     * @param string $sort
     * @return Paginator
     */
    public function listGroups($page=1, $max=10, $sort= 'id', $query= 'q', $admin = false)
    {
        $list = $this->createQueryBuilder('g');
        if (!$admin) {
            $list->where('g.isActive = :is_active')
                 ->setParameter('is_active', true);
        }
        if (!empty($query) && $query != 'q') {
            $list->andWhere('g.name LIKE :query OR g.description LIKE :query')
                 ->setParameter('query', '%' . $query . '%');
        }
        
        $list->orderBy('g.' . $sort, 'DESC');
 
        $list->setFirstResult(($page-1) * $max);
        $list->setMaxResults($max);
 
        return new Paginator($list);
    }
    
    /**
     * Gets the list of groups associated with a user
     *
     * @return array
     */
    public function findGroupsByUser($userid)
    {
        $groups = $this->createQueryBuilder('g')
                       ->join('g.users', 'gu')
                       ->where('gu.user = :id')
                       ->setParameter('id', $userid);
                
        $groups->orderBy('g.name', 'ASC');
        
        $query = $groups->getQuery();
        
        return $query->getResult();
    }
    
    /**
     * Get the template permissions for different groups
     *
     * @return array
     */
    public function accessList($templateId)
    {
        $access = $this->createQueryBuilder('g')
                       ->select('g', 'a')
                       ->where('g.isActive = 1')
                       ->leftJoin('g.permissions', 'a', 'WITH', 'a.template = :templateId')
                       ->setParameter('templateId', $templateId);
        $query = $access->getQuery();
        
        return $query->getResult();
        
    }
    
    /**
     * Gets the list of users associated with a template via a group
     *
     * @return array
     */
    public function findTemplateAccessGroupsByUser($id, $templateId)
    {
        $groups = $this->createQueryBuilder('g')
                       ->join('g.permissions', 'tag')
                       ->join('g.users', 'u')
                       ->where('g.isActive = 1')
                       ->andWhere('tag.template = :templateId')
                       ->andWhere('tag.read = 1')
                       ->andWhere('u.user = :id')
                       ->setParameter('templateId', $templateId)
                       ->setParameter('id', $id)
                       ->getQuery();

        return $groups->getResult();
    }

    public function findAllGroupsNotInArea($areaId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT g FROM NononsenseGroupBundle:Groups g 
                 WHERE  g.isActive = true AND g.id NOT IN
                (SELECT  IDENTITY(ag.agroup) FROM NononsenseHomeBundle:AreasGroups ag WHERE ag.area = :id)'
            )->setParameter('id', $areaId);
        //comment: the IDENTITY operator was need because it was a composite field
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function listGroupsByAreaAndPermission($area,$permission)
    {
        $groups = $this->createQueryBuilder('g')
            ->select('g.name', 'g.id')
            ->join('g.areas', 'a')
            ->join('g.groupsSubsecciones', 'gs')
            ->join('gs.subseccion', 's')
            ->where('a.area = :area')
            ->andWhere('s.nameId = :permission')
            ->andWhere('g.isActive = true')
            ->setParameter('area', $area)
            ->setParameter('permission', $permission)
            ->orderBy('g.name', 'ASC');

        return $groups->getQuery()->getArrayResult();

    }
}
